// Code generated by counterfeiter. DO NOT EDIT.
package networkfakes

import (
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/services/network/driver"
)

type Envelope struct {
	BytesStub        func() ([]byte, error)
	bytesMutex       sync.RWMutex
	bytesArgsForCall []struct {
	}
	bytesReturns struct {
		result1 []byte
		result2 error
	}
	bytesReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	FromBytesStub        func([]byte) error
	fromBytesMutex       sync.RWMutex
	fromBytesArgsForCall []struct {
		arg1 []byte
	}
	fromBytesReturns struct {
		result1 error
	}
	fromBytesReturnsOnCall map[int]struct {
		result1 error
	}
	StringStub        func() string
	stringMutex       sync.RWMutex
	stringArgsForCall []struct {
	}
	stringReturns struct {
		result1 string
	}
	stringReturnsOnCall map[int]struct {
		result1 string
	}
	TxIDStub        func() string
	txIDMutex       sync.RWMutex
	txIDArgsForCall []struct {
	}
	txIDReturns struct {
		result1 string
	}
	txIDReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Envelope) Bytes() ([]byte, error) {
	fake.bytesMutex.Lock()
	ret, specificReturn := fake.bytesReturnsOnCall[len(fake.bytesArgsForCall)]
	fake.bytesArgsForCall = append(fake.bytesArgsForCall, struct {
	}{})
	stub := fake.BytesStub
	fakeReturns := fake.bytesReturns
	fake.recordInvocation("Bytes", []interface{}{})
	fake.bytesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Envelope) BytesCallCount() int {
	fake.bytesMutex.RLock()
	defer fake.bytesMutex.RUnlock()
	return len(fake.bytesArgsForCall)
}

func (fake *Envelope) BytesCalls(stub func() ([]byte, error)) {
	fake.bytesMutex.Lock()
	defer fake.bytesMutex.Unlock()
	fake.BytesStub = stub
}

func (fake *Envelope) BytesReturns(result1 []byte, result2 error) {
	fake.bytesMutex.Lock()
	defer fake.bytesMutex.Unlock()
	fake.BytesStub = nil
	fake.bytesReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *Envelope) BytesReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.bytesMutex.Lock()
	defer fake.bytesMutex.Unlock()
	fake.BytesStub = nil
	if fake.bytesReturnsOnCall == nil {
		fake.bytesReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.bytesReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *Envelope) FromBytes(arg1 []byte) error {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.fromBytesMutex.Lock()
	ret, specificReturn := fake.fromBytesReturnsOnCall[len(fake.fromBytesArgsForCall)]
	fake.fromBytesArgsForCall = append(fake.fromBytesArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.FromBytesStub
	fakeReturns := fake.fromBytesReturns
	fake.recordInvocation("FromBytes", []interface{}{arg1Copy})
	fake.fromBytesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Envelope) FromBytesCallCount() int {
	fake.fromBytesMutex.RLock()
	defer fake.fromBytesMutex.RUnlock()
	return len(fake.fromBytesArgsForCall)
}

func (fake *Envelope) FromBytesCalls(stub func([]byte) error) {
	fake.fromBytesMutex.Lock()
	defer fake.fromBytesMutex.Unlock()
	fake.FromBytesStub = stub
}

func (fake *Envelope) FromBytesArgsForCall(i int) []byte {
	fake.fromBytesMutex.RLock()
	defer fake.fromBytesMutex.RUnlock()
	argsForCall := fake.fromBytesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Envelope) FromBytesReturns(result1 error) {
	fake.fromBytesMutex.Lock()
	defer fake.fromBytesMutex.Unlock()
	fake.FromBytesStub = nil
	fake.fromBytesReturns = struct {
		result1 error
	}{result1}
}

func (fake *Envelope) FromBytesReturnsOnCall(i int, result1 error) {
	fake.fromBytesMutex.Lock()
	defer fake.fromBytesMutex.Unlock()
	fake.FromBytesStub = nil
	if fake.fromBytesReturnsOnCall == nil {
		fake.fromBytesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fromBytesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Envelope) String() string {
	fake.stringMutex.Lock()
	ret, specificReturn := fake.stringReturnsOnCall[len(fake.stringArgsForCall)]
	fake.stringArgsForCall = append(fake.stringArgsForCall, struct {
	}{})
	stub := fake.StringStub
	fakeReturns := fake.stringReturns
	fake.recordInvocation("String", []interface{}{})
	fake.stringMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Envelope) StringCallCount() int {
	fake.stringMutex.RLock()
	defer fake.stringMutex.RUnlock()
	return len(fake.stringArgsForCall)
}

func (fake *Envelope) StringCalls(stub func() string) {
	fake.stringMutex.Lock()
	defer fake.stringMutex.Unlock()
	fake.StringStub = stub
}

func (fake *Envelope) StringReturns(result1 string) {
	fake.stringMutex.Lock()
	defer fake.stringMutex.Unlock()
	fake.StringStub = nil
	fake.stringReturns = struct {
		result1 string
	}{result1}
}

func (fake *Envelope) StringReturnsOnCall(i int, result1 string) {
	fake.stringMutex.Lock()
	defer fake.stringMutex.Unlock()
	fake.StringStub = nil
	if fake.stringReturnsOnCall == nil {
		fake.stringReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.stringReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *Envelope) TxID() string {
	fake.txIDMutex.Lock()
	ret, specificReturn := fake.txIDReturnsOnCall[len(fake.txIDArgsForCall)]
	fake.txIDArgsForCall = append(fake.txIDArgsForCall, struct {
	}{})
	stub := fake.TxIDStub
	fakeReturns := fake.txIDReturns
	fake.recordInvocation("TxID", []interface{}{})
	fake.txIDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Envelope) TxIDCallCount() int {
	fake.txIDMutex.RLock()
	defer fake.txIDMutex.RUnlock()
	return len(fake.txIDArgsForCall)
}

func (fake *Envelope) TxIDCalls(stub func() string) {
	fake.txIDMutex.Lock()
	defer fake.txIDMutex.Unlock()
	fake.TxIDStub = stub
}

func (fake *Envelope) TxIDReturns(result1 string) {
	fake.txIDMutex.Lock()
	defer fake.txIDMutex.Unlock()
	fake.TxIDStub = nil
	fake.txIDReturns = struct {
		result1 string
	}{result1}
}

func (fake *Envelope) TxIDReturnsOnCall(i int, result1 string) {
	fake.txIDMutex.Lock()
	defer fake.txIDMutex.Unlock()
	fake.TxIDStub = nil
	if fake.txIDReturnsOnCall == nil {
		fake.txIDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.txIDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *Envelope) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Envelope) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.Envelope = new(Envelope)
