// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/services/identity/role"
)

type WalletsConfiguration struct {
	CacheSizeForOwnerIDStub        func(string) int
	cacheSizeForOwnerIDMutex       sync.RWMutex
	cacheSizeForOwnerIDArgsForCall []struct {
		arg1 string
	}
	cacheSizeForOwnerIDReturns struct {
		result1 int
	}
	cacheSizeForOwnerIDReturnsOnCall map[int]struct {
		result1 int
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *WalletsConfiguration) CacheSizeForOwnerID(arg1 string) int {
	fake.cacheSizeForOwnerIDMutex.Lock()
	ret, specificReturn := fake.cacheSizeForOwnerIDReturnsOnCall[len(fake.cacheSizeForOwnerIDArgsForCall)]
	fake.cacheSizeForOwnerIDArgsForCall = append(fake.cacheSizeForOwnerIDArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CacheSizeForOwnerIDStub
	fakeReturns := fake.cacheSizeForOwnerIDReturns
	fake.recordInvocation("CacheSizeForOwnerID", []interface{}{arg1})
	fake.cacheSizeForOwnerIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *WalletsConfiguration) CacheSizeForOwnerIDCallCount() int {
	fake.cacheSizeForOwnerIDMutex.RLock()
	defer fake.cacheSizeForOwnerIDMutex.RUnlock()
	return len(fake.cacheSizeForOwnerIDArgsForCall)
}

func (fake *WalletsConfiguration) CacheSizeForOwnerIDCalls(stub func(string) int) {
	fake.cacheSizeForOwnerIDMutex.Lock()
	defer fake.cacheSizeForOwnerIDMutex.Unlock()
	fake.CacheSizeForOwnerIDStub = stub
}

func (fake *WalletsConfiguration) CacheSizeForOwnerIDArgsForCall(i int) string {
	fake.cacheSizeForOwnerIDMutex.RLock()
	defer fake.cacheSizeForOwnerIDMutex.RUnlock()
	argsForCall := fake.cacheSizeForOwnerIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *WalletsConfiguration) CacheSizeForOwnerIDReturns(result1 int) {
	fake.cacheSizeForOwnerIDMutex.Lock()
	defer fake.cacheSizeForOwnerIDMutex.Unlock()
	fake.CacheSizeForOwnerIDStub = nil
	fake.cacheSizeForOwnerIDReturns = struct {
		result1 int
	}{result1}
}

func (fake *WalletsConfiguration) CacheSizeForOwnerIDReturnsOnCall(i int, result1 int) {
	fake.cacheSizeForOwnerIDMutex.Lock()
	defer fake.cacheSizeForOwnerIDMutex.Unlock()
	fake.CacheSizeForOwnerIDStub = nil
	if fake.cacheSizeForOwnerIDReturnsOnCall == nil {
		fake.cacheSizeForOwnerIDReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.cacheSizeForOwnerIDReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *WalletsConfiguration) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *WalletsConfiguration) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ role.WalletsConfiguration = new(WalletsConfiguration)
