// Code generated by counterfeiter. DO NOT EDIT.
package nfttxfakes

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/token"
)

type Vault struct {
	GetTokensStub        func(context.Context, ...*token.ID) ([]*token.Token, error)
	getTokensMutex       sync.RWMutex
	getTokensArgsForCall []struct {
		arg1 context.Context
		arg2 []*token.ID
	}
	getTokensReturns struct {
		result1 []*token.Token
		result2 error
	}
	getTokensReturnsOnCall map[int]struct {
		result1 []*token.Token
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Vault) GetTokens(arg1 context.Context, arg2 ...*token.ID) ([]*token.Token, error) {
	fake.getTokensMutex.Lock()
	ret, specificReturn := fake.getTokensReturnsOnCall[len(fake.getTokensArgsForCall)]
	fake.getTokensArgsForCall = append(fake.getTokensArgsForCall, struct {
		arg1 context.Context
		arg2 []*token.ID
	}{arg1, arg2})
	stub := fake.GetTokensStub
	fakeReturns := fake.getTokensReturns
	fake.recordInvocation("GetTokens", []interface{}{arg1, arg2})
	fake.getTokensMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Vault) GetTokensCallCount() int {
	fake.getTokensMutex.RLock()
	defer fake.getTokensMutex.RUnlock()
	return len(fake.getTokensArgsForCall)
}

func (fake *Vault) GetTokensCalls(stub func(context.Context, ...*token.ID) ([]*token.Token, error)) {
	fake.getTokensMutex.Lock()
	defer fake.getTokensMutex.Unlock()
	fake.GetTokensStub = stub
}

func (fake *Vault) GetTokensArgsForCall(i int) (context.Context, []*token.ID) {
	fake.getTokensMutex.RLock()
	defer fake.getTokensMutex.RUnlock()
	argsForCall := fake.getTokensArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Vault) GetTokensReturns(result1 []*token.Token, result2 error) {
	fake.getTokensMutex.Lock()
	defer fake.getTokensMutex.Unlock()
	fake.GetTokensStub = nil
	fake.getTokensReturns = struct {
		result1 []*token.Token
		result2 error
	}{result1, result2}
}

func (fake *Vault) GetTokensReturnsOnCall(i int, result1 []*token.Token, result2 error) {
	fake.getTokensMutex.Lock()
	defer fake.getTokensMutex.Unlock()
	fake.GetTokensStub = nil
	if fake.getTokensReturnsOnCall == nil {
		fake.getTokensReturnsOnCall = make(map[int]struct {
			result1 []*token.Token
			result2 error
		})
	}
	fake.getTokensReturnsOnCall[i] = struct {
		result1 []*token.Token
		result2 error
	}{result1, result2}
}

func (fake *Vault) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Vault) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
