@startuml
'- force wrapping of longer text
'skinparam wrapWidth 400
!pragma teoz true
hide footbox

actor "Seller" as Seller
actor "Buyer" as Buyer
participant "Ordering Service" as Orderer

group Assemble Transaction
Seller->Buyer: Send House's valuation
Buyer->Buyer: Prepare Transfer
Buyer->Seller: Send Transfer
Seller->Seller: Assemble Transaction
end group
group Collect Signatures
Seller->Buyer: Ask for signature
Buyer->Buyer: Inspect Tx.\nSign if valid
Buyer->Seller: Signed Transaction
Seller->Seller: Inspect Tx.\nSign if valid
end group
group Ordering
Seller->Orderer: Ask for Ordering
end group
@enduml