//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: ftactions.proto

package actions

import (
	pp "github.com/hyperledger-labs/fabric-token-sdk/token/core/fabtoken/protos-go/pp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner    []byte `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`       // is the token owner
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`         // is the type of the token
	Quantity string `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"` // is the number of units of Type carried in the token. It is encoded as a string containing a number in base 16. The string has prefix ``0x''.
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftactions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Token) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Token) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type TokenID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *TokenID) Reset() {
	*x = TokenID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftactions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenID) ProtoMessage() {}

func (x *TokenID) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenID.ProtoReflect.Descriptor instead.
func (*TokenID) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{1}
}

func (x *TokenID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenID) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type TransferActionInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId *TokenID `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Input   *Token   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *TransferActionInput) Reset() {
	*x = TransferActionInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftactions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferActionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferActionInput) ProtoMessage() {}

func (x *TransferActionInput) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferActionInput.ProtoReflect.Descriptor instead.
func (*TransferActionInput) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{2}
}

func (x *TransferActionInput) GetTokenId() *TokenID {
	if x != nil {
		return x.TokenId
	}
	return nil
}

func (x *TransferActionInput) GetInput() *Token {
	if x != nil {
		return x.Input
	}
	return nil
}

type TransferActionOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // Token is the new token
}

func (x *TransferActionOutput) Reset() {
	*x = TransferActionOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftactions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferActionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferActionOutput) ProtoMessage() {}

func (x *TransferActionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferActionOutput.ProtoReflect.Descriptor instead.
func (*TransferActionOutput) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{3}
}

func (x *TransferActionOutput) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type TransferAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  uint64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Inputs   []*TransferActionInput  `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`                                                                                             // inputs
	Outputs  []*TransferActionOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`                                                                                           // outputs
	Metadata map[string][]byte       `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Metadata contains the transfer action's metadata
	Issuer   *pp.Identity            `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`                                                                                             // is the identity of issuer to sign the transfer action
}

func (x *TransferAction) Reset() {
	*x = TransferAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftactions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAction) ProtoMessage() {}

func (x *TransferAction) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAction.ProtoReflect.Descriptor instead.
func (*TransferAction) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{4}
}

func (x *TransferAction) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TransferAction) GetInputs() []*TransferActionInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *TransferAction) GetOutputs() []*TransferActionOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TransferAction) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TransferAction) GetIssuer() *pp.Identity {
	if x != nil {
		return x.Issuer
	}
	return nil
}

type IssueActionInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *TokenID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // is the token id of the token to be redeemed
	Token []byte   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // is the actual token to be redeemed
}

func (x *IssueActionInput) Reset() {
	*x = IssueActionInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftactions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueActionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueActionInput) ProtoMessage() {}

func (x *IssueActionInput) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueActionInput.ProtoReflect.Descriptor instead.
func (*IssueActionInput) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{5}
}

func (x *IssueActionInput) GetId() *TokenID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *IssueActionInput) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type IssueActionOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // is the newly issued token
}

func (x *IssueActionOutput) Reset() {
	*x = IssueActionOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftactions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueActionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueActionOutput) ProtoMessage() {}

func (x *IssueActionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueActionOutput.ProtoReflect.Descriptor instead.
func (*IssueActionOutput) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{6}
}

func (x *IssueActionOutput) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type IssueAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  uint64               `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Issuer   *pp.Identity         `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`                                                                                             // is the identity of issuer
	Inputs   []*IssueActionInput  `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`                                                                                             // are the tokens to be redeemed by this issue action
	Outputs  []*IssueActionOutput `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`                                                                                           // are the newly issued tokens
	Metadata map[string][]byte    `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Metadata of the issue action
}

func (x *IssueAction) Reset() {
	*x = IssueAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftactions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAction) ProtoMessage() {}

func (x *IssueAction) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAction.ProtoReflect.Descriptor instead.
func (*IssueAction) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{7}
}

func (x *IssueAction) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *IssueAction) GetIssuer() *pp.Identity {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *IssueAction) GetInputs() []*IssueActionInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *IssueAction) GetOutputs() []*IssueActionOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *IssueAction) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_ftactions_proto protoreflect.FileDescriptor

var file_ftactions_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x74, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x66, 0x61, 0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x0a, 0x66, 0x74, 0x70,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x2f, 0x0a, 0x07, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49,
	0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x6a, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x2c,
	0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x66, 0x61, 0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x49, 0x44, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61,
	0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x22, 0x3d, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x61, 0x62,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0xc8, 0x02, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x35, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x66, 0x61, 0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x06,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x61, 0x62, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73,
	0x12, 0x42, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x66, 0x61, 0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x61, 0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72,
	0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4b, 0x0a,
	0x10, 0x49, 0x73, 0x73, 0x75, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x66, 0x61, 0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x44,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3a, 0x0a, 0x11, 0x49, 0x73,
	0x73, 0x75, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x25, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x66, 0x61, 0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xbc, 0x02, 0x0a, 0x0b, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x2a, 0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x66, 0x61, 0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x06,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66,
	0x61, 0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73,
	0x12, 0x35, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x61, 0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x07,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x66, 0x61, 0x62, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x54, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2d,
	0x6c, 0x61, 0x62, 0x73, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x2d, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x66, 0x61, 0x62, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ftactions_proto_rawDescOnce sync.Once
	file_ftactions_proto_rawDescData = file_ftactions_proto_rawDesc
)

func file_ftactions_proto_rawDescGZIP() []byte {
	file_ftactions_proto_rawDescOnce.Do(func() {
		file_ftactions_proto_rawDescData = protoimpl.X.CompressGZIP(file_ftactions_proto_rawDescData)
	})
	return file_ftactions_proto_rawDescData
}

var file_ftactions_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ftactions_proto_goTypes = []any{
	(*Token)(nil),                // 0: fabtoken.Token
	(*TokenID)(nil),              // 1: fabtoken.TokenID
	(*TransferActionInput)(nil),  // 2: fabtoken.TransferActionInput
	(*TransferActionOutput)(nil), // 3: fabtoken.TransferActionOutput
	(*TransferAction)(nil),       // 4: fabtoken.TransferAction
	(*IssueActionInput)(nil),     // 5: fabtoken.IssueActionInput
	(*IssueActionOutput)(nil),    // 6: fabtoken.IssueActionOutput
	(*IssueAction)(nil),          // 7: fabtoken.IssueAction
	nil,                          // 8: fabtoken.TransferAction.MetadataEntry
	nil,                          // 9: fabtoken.IssueAction.MetadataEntry
	(*pp.Identity)(nil),          // 10: fabtoken.Identity
}
var file_ftactions_proto_depIdxs = []int32{
	1,  // 0: fabtoken.TransferActionInput.token_id:type_name -> fabtoken.TokenID
	0,  // 1: fabtoken.TransferActionInput.input:type_name -> fabtoken.Token
	0,  // 2: fabtoken.TransferActionOutput.token:type_name -> fabtoken.Token
	2,  // 3: fabtoken.TransferAction.inputs:type_name -> fabtoken.TransferActionInput
	3,  // 4: fabtoken.TransferAction.outputs:type_name -> fabtoken.TransferActionOutput
	8,  // 5: fabtoken.TransferAction.metadata:type_name -> fabtoken.TransferAction.MetadataEntry
	10, // 6: fabtoken.TransferAction.issuer:type_name -> fabtoken.Identity
	1,  // 7: fabtoken.IssueActionInput.id:type_name -> fabtoken.TokenID
	0,  // 8: fabtoken.IssueActionOutput.token:type_name -> fabtoken.Token
	10, // 9: fabtoken.IssueAction.issuer:type_name -> fabtoken.Identity
	5,  // 10: fabtoken.IssueAction.inputs:type_name -> fabtoken.IssueActionInput
	6,  // 11: fabtoken.IssueAction.outputs:type_name -> fabtoken.IssueActionOutput
	9,  // 12: fabtoken.IssueAction.metadata:type_name -> fabtoken.IssueAction.MetadataEntry
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_ftactions_proto_init() }
func file_ftactions_proto_init() {
	if File_ftactions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ftactions_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ftactions_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TokenID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ftactions_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TransferActionInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ftactions_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TransferActionOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ftactions_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TransferAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ftactions_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*IssueActionInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ftactions_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*IssueActionOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ftactions_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*IssueAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ftactions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ftactions_proto_goTypes,
		DependencyIndexes: file_ftactions_proto_depIdxs,
		MessageInfos:      file_ftactions_proto_msgTypes,
	}.Build()
	File_ftactions_proto = out.File
	file_ftactions_proto_rawDesc = nil
	file_ftactions_proto_goTypes = nil
	file_ftactions_proto_depIdxs = nil
}
