// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/fabric/services/endorser"
	"github.com/hyperledger-labs/fabric-smart-client/platform/view/view"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/network/fabric/endorsement/fsc"
)

type EndorserService struct {
	EndorseStub        func(*endorser.Transaction, ...view.Identity) (any, error)
	endorseMutex       sync.RWMutex
	endorseArgsForCall []struct {
		arg1 *endorser.Transaction
		arg2 []view.Identity
	}
	endorseReturns struct {
		result1 any
		result2 error
	}
	endorseReturnsOnCall map[int]struct {
		result1 any
		result2 error
	}
	ReceiveTxStub        func(view.Context) (*endorser.Transaction, error)
	receiveTxMutex       sync.RWMutex
	receiveTxArgsForCall []struct {
		arg1 view.Context
	}
	receiveTxReturns struct {
		result1 *endorser.Transaction
		result2 error
	}
	receiveTxReturnsOnCall map[int]struct {
		result1 *endorser.Transaction
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *EndorserService) Endorse(arg1 *endorser.Transaction, arg2 ...view.Identity) (any, error) {
	fake.endorseMutex.Lock()
	ret, specificReturn := fake.endorseReturnsOnCall[len(fake.endorseArgsForCall)]
	fake.endorseArgsForCall = append(fake.endorseArgsForCall, struct {
		arg1 *endorser.Transaction
		arg2 []view.Identity
	}{arg1, arg2})
	stub := fake.EndorseStub
	fakeReturns := fake.endorseReturns
	fake.recordInvocation("Endorse", []interface{}{arg1, arg2})
	fake.endorseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EndorserService) EndorseCallCount() int {
	fake.endorseMutex.RLock()
	defer fake.endorseMutex.RUnlock()
	return len(fake.endorseArgsForCall)
}

func (fake *EndorserService) EndorseCalls(stub func(*endorser.Transaction, ...view.Identity) (any, error)) {
	fake.endorseMutex.Lock()
	defer fake.endorseMutex.Unlock()
	fake.EndorseStub = stub
}

func (fake *EndorserService) EndorseArgsForCall(i int) (*endorser.Transaction, []view.Identity) {
	fake.endorseMutex.RLock()
	defer fake.endorseMutex.RUnlock()
	argsForCall := fake.endorseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *EndorserService) EndorseReturns(result1 any, result2 error) {
	fake.endorseMutex.Lock()
	defer fake.endorseMutex.Unlock()
	fake.EndorseStub = nil
	fake.endorseReturns = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *EndorserService) EndorseReturnsOnCall(i int, result1 any, result2 error) {
	fake.endorseMutex.Lock()
	defer fake.endorseMutex.Unlock()
	fake.EndorseStub = nil
	if fake.endorseReturnsOnCall == nil {
		fake.endorseReturnsOnCall = make(map[int]struct {
			result1 any
			result2 error
		})
	}
	fake.endorseReturnsOnCall[i] = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *EndorserService) ReceiveTx(arg1 view.Context) (*endorser.Transaction, error) {
	fake.receiveTxMutex.Lock()
	ret, specificReturn := fake.receiveTxReturnsOnCall[len(fake.receiveTxArgsForCall)]
	fake.receiveTxArgsForCall = append(fake.receiveTxArgsForCall, struct {
		arg1 view.Context
	}{arg1})
	stub := fake.ReceiveTxStub
	fakeReturns := fake.receiveTxReturns
	fake.recordInvocation("ReceiveTx", []interface{}{arg1})
	fake.receiveTxMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EndorserService) ReceiveTxCallCount() int {
	fake.receiveTxMutex.RLock()
	defer fake.receiveTxMutex.RUnlock()
	return len(fake.receiveTxArgsForCall)
}

func (fake *EndorserService) ReceiveTxCalls(stub func(view.Context) (*endorser.Transaction, error)) {
	fake.receiveTxMutex.Lock()
	defer fake.receiveTxMutex.Unlock()
	fake.ReceiveTxStub = stub
}

func (fake *EndorserService) ReceiveTxArgsForCall(i int) view.Context {
	fake.receiveTxMutex.RLock()
	defer fake.receiveTxMutex.RUnlock()
	argsForCall := fake.receiveTxArgsForCall[i]
	return argsForCall.arg1
}

func (fake *EndorserService) ReceiveTxReturns(result1 *endorser.Transaction, result2 error) {
	fake.receiveTxMutex.Lock()
	defer fake.receiveTxMutex.Unlock()
	fake.ReceiveTxStub = nil
	fake.receiveTxReturns = struct {
		result1 *endorser.Transaction
		result2 error
	}{result1, result2}
}

func (fake *EndorserService) ReceiveTxReturnsOnCall(i int, result1 *endorser.Transaction, result2 error) {
	fake.receiveTxMutex.Lock()
	defer fake.receiveTxMutex.Unlock()
	fake.ReceiveTxStub = nil
	if fake.receiveTxReturnsOnCall == nil {
		fake.receiveTxReturnsOnCall = make(map[int]struct {
			result1 *endorser.Transaction
			result2 error
		})
	}
	fake.receiveTxReturnsOnCall[i] = struct {
		result1 *endorser.Transaction
		result2 error
	}{result1, result2}
}

func (fake *EndorserService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.endorseMutex.RLock()
	defer fake.endorseMutex.RUnlock()
	fake.receiveTxMutex.RLock()
	defer fake.receiveTxMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *EndorserService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fsc.EndorserService = new(EndorserService)
