// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/network/fabric/endorsement/fsc"
)

type Storage struct {
	AppendValidationRecordStub        func(context.Context, string, []byte, map[string][]byte, driver.PPHash) error
	appendValidationRecordMutex       sync.RWMutex
	appendValidationRecordArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
		arg4 map[string][]byte
		arg5 driver.PPHash
	}
	appendValidationRecordReturns struct {
		result1 error
	}
	appendValidationRecordReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Storage) AppendValidationRecord(arg1 context.Context, arg2 string, arg3 []byte, arg4 map[string][]byte, arg5 driver.PPHash) error {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.appendValidationRecordMutex.Lock()
	ret, specificReturn := fake.appendValidationRecordReturnsOnCall[len(fake.appendValidationRecordArgsForCall)]
	fake.appendValidationRecordArgsForCall = append(fake.appendValidationRecordArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []byte
		arg4 map[string][]byte
		arg5 driver.PPHash
	}{arg1, arg2, arg3Copy, arg4, arg5})
	stub := fake.AppendValidationRecordStub
	fakeReturns := fake.appendValidationRecordReturns
	fake.recordInvocation("AppendValidationRecord", []interface{}{arg1, arg2, arg3Copy, arg4, arg5})
	fake.appendValidationRecordMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Storage) AppendValidationRecordCallCount() int {
	fake.appendValidationRecordMutex.RLock()
	defer fake.appendValidationRecordMutex.RUnlock()
	return len(fake.appendValidationRecordArgsForCall)
}

func (fake *Storage) AppendValidationRecordCalls(stub func(context.Context, string, []byte, map[string][]byte, driver.PPHash) error) {
	fake.appendValidationRecordMutex.Lock()
	defer fake.appendValidationRecordMutex.Unlock()
	fake.AppendValidationRecordStub = stub
}

func (fake *Storage) AppendValidationRecordArgsForCall(i int) (context.Context, string, []byte, map[string][]byte, driver.PPHash) {
	fake.appendValidationRecordMutex.RLock()
	defer fake.appendValidationRecordMutex.RUnlock()
	argsForCall := fake.appendValidationRecordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *Storage) AppendValidationRecordReturns(result1 error) {
	fake.appendValidationRecordMutex.Lock()
	defer fake.appendValidationRecordMutex.Unlock()
	fake.AppendValidationRecordStub = nil
	fake.appendValidationRecordReturns = struct {
		result1 error
	}{result1}
}

func (fake *Storage) AppendValidationRecordReturnsOnCall(i int, result1 error) {
	fake.appendValidationRecordMutex.Lock()
	defer fake.appendValidationRecordMutex.Unlock()
	fake.AppendValidationRecordStub = nil
	if fake.appendValidationRecordReturnsOnCall == nil {
		fake.appendValidationRecordReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.appendValidationRecordReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Storage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.appendValidationRecordMutex.RLock()
	defer fake.appendValidationRecordMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Storage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fsc.Storage = new(Storage)
