// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/network/fabric/endorsement/fsc"
)

type StorageProvider struct {
	GetStorageStub        func(token.TMSID) (fsc.Storage, error)
	getStorageMutex       sync.RWMutex
	getStorageArgsForCall []struct {
		arg1 token.TMSID
	}
	getStorageReturns struct {
		result1 fsc.Storage
		result2 error
	}
	getStorageReturnsOnCall map[int]struct {
		result1 fsc.Storage
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *StorageProvider) GetStorage(arg1 token.TMSID) (fsc.Storage, error) {
	fake.getStorageMutex.Lock()
	ret, specificReturn := fake.getStorageReturnsOnCall[len(fake.getStorageArgsForCall)]
	fake.getStorageArgsForCall = append(fake.getStorageArgsForCall, struct {
		arg1 token.TMSID
	}{arg1})
	stub := fake.GetStorageStub
	fakeReturns := fake.getStorageReturns
	fake.recordInvocation("GetStorage", []interface{}{arg1})
	fake.getStorageMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *StorageProvider) GetStorageCallCount() int {
	fake.getStorageMutex.RLock()
	defer fake.getStorageMutex.RUnlock()
	return len(fake.getStorageArgsForCall)
}

func (fake *StorageProvider) GetStorageCalls(stub func(token.TMSID) (fsc.Storage, error)) {
	fake.getStorageMutex.Lock()
	defer fake.getStorageMutex.Unlock()
	fake.GetStorageStub = stub
}

func (fake *StorageProvider) GetStorageArgsForCall(i int) token.TMSID {
	fake.getStorageMutex.RLock()
	defer fake.getStorageMutex.RUnlock()
	argsForCall := fake.getStorageArgsForCall[i]
	return argsForCall.arg1
}

func (fake *StorageProvider) GetStorageReturns(result1 fsc.Storage, result2 error) {
	fake.getStorageMutex.Lock()
	defer fake.getStorageMutex.Unlock()
	fake.GetStorageStub = nil
	fake.getStorageReturns = struct {
		result1 fsc.Storage
		result2 error
	}{result1, result2}
}

func (fake *StorageProvider) GetStorageReturnsOnCall(i int, result1 fsc.Storage, result2 error) {
	fake.getStorageMutex.Lock()
	defer fake.getStorageMutex.Unlock()
	fake.GetStorageStub = nil
	if fake.getStorageReturnsOnCall == nil {
		fake.getStorageReturnsOnCall = make(map[int]struct {
			result1 fsc.Storage
			result2 error
		})
	}
	fake.getStorageReturnsOnCall[i] = struct {
		result1 fsc.Storage
		result2 error
	}{result1, result2}
}

func (fake *StorageProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getStorageMutex.RLock()
	defer fake.getStorageMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *StorageProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ fsc.StorageProvider = new(StorageProvider)
