/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package regression_test

import (
	"embed"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"path/filepath"
	"testing"

	"github.com/hyperledger-labs/fabric-token-sdk/token"
	"github.com/hyperledger-labs/fabric-token-sdk/token/core"
	fabtoken "github.com/hyperledger-labs/fabric-token-sdk/token/core/fabtoken/v1/driver"
	dlog "github.com/hyperledger-labs/fabric-token-sdk/token/core/zkatdlog/nogh/v1/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/network/fabric/tcc"
	tk "github.com/hyperledger-labs/fabric-token-sdk/token/token"
	"github.com/stretchr/testify/require"
)

//go:embed testdata testdata2 testdata3
var testDataFS embed.FS

// TestRegression runs previously recorded regression test vectors contained in the
// `testdata/<variant>`, `testdata2/<variant>`, and `testdata3old/<variant>` directories.
// Each directory contains a `params.txt` and a
// sequence of JSON files under `transfers/output.<n>.json` representing serialized
// token requests and their associated txids. The test unmarshals each recorded
// request and verifies it against the validator to ensure the library remains
// backwards compatible.
//
// Notes:
//   - The testdata used here is generated by `testdata/generator` or alike. If you need to
//     re-generate vectors for a new setup, run that generator and commit the
//     produced artifacts to the corresponding `testdata/...` or alike directory.
//   - The test expects 64 transfer vectors (output.0..output.63). Update the loop
//     range in `testRegression` if you add or remove vectors.
func TestRegression(t *testing.T) {
	t.Parallel()
	for _, root := range []string{"testdata", "testdata2", "testdata3"} {
		for _, action := range []string{"transfers", "issues", "redeems", "swaps"} {
			testRegressionParallel(t, filepath.Join(root, "32-BLS12_381_BBS_GURVY"), action+"_i1_o1")
			testRegressionParallel(t, filepath.Join(root, "32-BLS12_381_BBS_GURVY"), action+"_i1_o2")
			testRegressionParallel(t, filepath.Join(root, "32-BLS12_381_BBS_GURVY"), action+"_i2_o1")
			testRegressionParallel(t, filepath.Join(root, "32-BLS12_381_BBS_GURVY"), action+"_i2_o2")

			testRegressionParallel(t, filepath.Join(root, "64-BLS12_381_BBS_GURVY"), action+"_i1_o1")
			testRegressionParallel(t, filepath.Join(root, "64-BLS12_381_BBS_GURVY"), action+"_i1_o2")
			testRegressionParallel(t, filepath.Join(root, "64-BLS12_381_BBS_GURVY"), action+"_i2_o1")
			testRegressionParallel(t, filepath.Join(root, "64-BLS12_381_BBS_GURVY"), action+"_i2_o2")

			testRegressionParallel(t, filepath.Join(root, "32-BN254"), action+"_i1_o1")
			testRegressionParallel(t, filepath.Join(root, "32-BN254"), action+"_i1_o2")
			testRegressionParallel(t, filepath.Join(root, "32-BN254"), action+"_i2_o1")
			testRegressionParallel(t, filepath.Join(root, "32-BN254"), action+"_i2_o2")

			testRegressionParallel(t, filepath.Join(root, "64-BN254"), action+"_i1_o1")
			testRegressionParallel(t, filepath.Join(root, "64-BN254"), action+"_i1_o2")
			testRegressionParallel(t, filepath.Join(root, "64-BN254"), action+"_i2_o1")
			testRegressionParallel(t, filepath.Join(root, "64-BN254"), action+"_i2_o2")
		}
	}
}

func testRegressionParallel(t *testing.T, rootDir, subFolder string) {
	t.Helper()
	t.Run(fmt.Sprintf("%s-%s", rootDir, subFolder), func(t *testing.T) {
		t.Parallel()
		testRegression(t, rootDir, subFolder)
	})
}

func testRegression(t *testing.T, rootDir, subFolder string) {
	t.Helper()
	t.Logf("regression test for [%s:%s]", rootDir, subFolder)
	paramsData, err := testDataFS.ReadFile(filepath.Join(rootDir, "params.txt"))
	require.NoError(t, err)

	ppRaw, err := base64.StdEncoding.DecodeString(string(paramsData))
	require.NoError(t, err)

	_, tokenValidator, err := tokenServicesFactory(ppRaw)
	require.NoError(t, err)

	var tokenData struct {
		ReqRaw []byte `json:"req_raw"`
		TXID   string `json:"txid"`
	}
	for i := range 64 {
		filePath := filepath.Join(
			rootDir,
			subFolder,
			fmt.Sprintf("output.%d.json", i),
		)
		jsonData, err := testDataFS.ReadFile(filePath)
		require.NoError(t, err)
		err = json.Unmarshal(jsonData, &tokenData)
		require.NoError(t, err)
		_, _, err = tokenValidator.UnmarshallAndVerifyWithMetadata(
			t.Context(),
			&fakeLedger{},
			token.RequestAnchor(tokenData.TXID),
			tokenData.ReqRaw,
		)
		require.NoError(t, err, "failed verification of the token request in [%s]", filePath)
	}
}

func tokenServicesFactory(bytes []byte) (tcc.PublicParameters, tcc.Validator, error) {
	is := core.NewValidatorDriverService(fabtoken.NewValidatorDriver(), dlog.NewValidatorDriver())

	ppm, err := is.PublicParametersFromBytes(bytes)
	if err != nil {
		return nil, nil, err
	}
	if err := ppm.Validate(); err != nil {
		return nil, nil, err
	}
	v, err := is.NewValidator(ppm)
	if err != nil {
		return nil, nil, err
	}

	return ppm, token.NewValidator(v), nil
}

type fakeLedger struct{}

func (*fakeLedger) GetState(_ tk.ID) ([]byte, error) {
	panic("ciao")
}

// TestRegressionWithMinProtocolVersionV2 verifies that when the validator is configured
// with MinProtocolVersion set to V2, all V1 token requests (from testdata) are rejected
// with the expected error message about protocol version being below minimum.
func TestRegressionWithMinProtocolVersionV2(t *testing.T) {
	t.Parallel()
	// Test with one representative sample from each testdata directory
	for _, root := range []string{"testdata", "testdata2", "testdata3"} {
		for _, variant := range []string{"32-BLS12_381_BBS_GURVY", "64-BLS12_381_BBS_GURVY", "32-BN254", "64-BN254"} {
			testRegressionWithMinVersionParallel(t, filepath.Join(root, variant), "transfers_i1_o1")
		}
	}
}

func testRegressionWithMinVersionParallel(t *testing.T, rootDir, subFolder string) {
	t.Helper()
	t.Run(fmt.Sprintf("%s-%s-MinV2", rootDir, subFolder), func(t *testing.T) {
		t.Parallel()
		testRegressionWithMinVersion(t, rootDir, subFolder)
	})
}

func testRegressionWithMinVersion(t *testing.T, rootDir, subFolder string) {
	t.Helper()
	t.Logf("regression test with MinProtocolVersion=V2 for [%s:%s]", rootDir, subFolder)

	paramsData, err := testDataFS.ReadFile(filepath.Join(rootDir, "params.txt"))
	require.NoError(t, err)

	ppRaw, err := base64.StdEncoding.DecodeString(string(paramsData))
	require.NoError(t, err)

	// Create validator with MinProtocolVersion set to V2
	_, tokenValidator, err := tokenServicesFactoryWithMinVersion(ppRaw, driver.ProtocolV2)
	require.NoError(t, err)

	var tokenData struct {
		ReqRaw []byte `json:"req_raw"`
		TXID   string `json:"txid"`
	}

	// Test just the first vector - all vectors in testdata are V1
	filePath := filepath.Join(rootDir, subFolder, "output.0.json")
	jsonData, err := testDataFS.ReadFile(filePath)
	require.NoError(t, err)

	err = json.Unmarshal(jsonData, &tokenData)
	require.NoError(t, err)

	// Verify that validation fails with the expected typed error
	_, _, err = tokenValidator.UnmarshallAndVerifyWithMetadata(
		t.Context(),
		&fakeLedger{},
		token.RequestAnchor(tokenData.TXID),
		tokenData.ReqRaw,
	)

	// Should fail because testdata contains V1 requests
	require.Error(t, err, "Expected validation to fail for V1 request when MinProtocolVersion=V2")
	require.ErrorIs(t, err, driver.ErrVersionBelowMinimum,
		"Error should be ErrVersionBelowMinimum, got: %v", err)
}

func tokenServicesFactoryWithMinVersion(bytes []byte, minVersion uint32) (tcc.PublicParameters, tcc.Validator, error) {
	is := core.NewPPManagerFactoryService(fabtoken.NewPPMFactory(), dlog.NewPPMFactory())

	ppm, err := is.PublicParametersFromBytes(bytes)
	if err != nil {
		return nil, nil, err
	}
	if err := ppm.Validate(); err != nil {
		return nil, nil, err
	}
	v, err := is.DefaultValidator(ppm)
	if err != nil {
		return nil, nil, err
	}

	// Set MinProtocolVersion on the validator using the new interface method
	v.SetMinProtocolVersion(minVersion)

	return ppm, token.NewValidator(v), nil
}
