// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/services/identity/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/identity/membership"
)

type Config struct {
	IdentitiesForRoleStub        func(driver.IdentityRoleType) ([]driver.ConfiguredIdentity, error)
	identitiesForRoleMutex       sync.RWMutex
	identitiesForRoleArgsForCall []struct {
		arg1 driver.IdentityRoleType
	}
	identitiesForRoleReturns struct {
		result1 []driver.ConfiguredIdentity
		result2 error
	}
	identitiesForRoleReturnsOnCall map[int]struct {
		result1 []driver.ConfiguredIdentity
		result2 error
	}
	TranslatePathStub        func(string) string
	translatePathMutex       sync.RWMutex
	translatePathArgsForCall []struct {
		arg1 string
	}
	translatePathReturns struct {
		result1 string
	}
	translatePathReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Config) IdentitiesForRole(arg1 driver.IdentityRoleType) ([]driver.ConfiguredIdentity, error) {
	fake.identitiesForRoleMutex.Lock()
	ret, specificReturn := fake.identitiesForRoleReturnsOnCall[len(fake.identitiesForRoleArgsForCall)]
	fake.identitiesForRoleArgsForCall = append(fake.identitiesForRoleArgsForCall, struct {
		arg1 driver.IdentityRoleType
	}{arg1})
	stub := fake.IdentitiesForRoleStub
	fakeReturns := fake.identitiesForRoleReturns
	fake.recordInvocation("IdentitiesForRole", []interface{}{arg1})
	fake.identitiesForRoleMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Config) IdentitiesForRoleCallCount() int {
	fake.identitiesForRoleMutex.RLock()
	defer fake.identitiesForRoleMutex.RUnlock()
	return len(fake.identitiesForRoleArgsForCall)
}

func (fake *Config) IdentitiesForRoleCalls(stub func(driver.IdentityRoleType) ([]driver.ConfiguredIdentity, error)) {
	fake.identitiesForRoleMutex.Lock()
	defer fake.identitiesForRoleMutex.Unlock()
	fake.IdentitiesForRoleStub = stub
}

func (fake *Config) IdentitiesForRoleArgsForCall(i int) driver.IdentityRoleType {
	fake.identitiesForRoleMutex.RLock()
	defer fake.identitiesForRoleMutex.RUnlock()
	argsForCall := fake.identitiesForRoleArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Config) IdentitiesForRoleReturns(result1 []driver.ConfiguredIdentity, result2 error) {
	fake.identitiesForRoleMutex.Lock()
	defer fake.identitiesForRoleMutex.Unlock()
	fake.IdentitiesForRoleStub = nil
	fake.identitiesForRoleReturns = struct {
		result1 []driver.ConfiguredIdentity
		result2 error
	}{result1, result2}
}

func (fake *Config) IdentitiesForRoleReturnsOnCall(i int, result1 []driver.ConfiguredIdentity, result2 error) {
	fake.identitiesForRoleMutex.Lock()
	defer fake.identitiesForRoleMutex.Unlock()
	fake.IdentitiesForRoleStub = nil
	if fake.identitiesForRoleReturnsOnCall == nil {
		fake.identitiesForRoleReturnsOnCall = make(map[int]struct {
			result1 []driver.ConfiguredIdentity
			result2 error
		})
	}
	fake.identitiesForRoleReturnsOnCall[i] = struct {
		result1 []driver.ConfiguredIdentity
		result2 error
	}{result1, result2}
}

func (fake *Config) TranslatePath(arg1 string) string {
	fake.translatePathMutex.Lock()
	ret, specificReturn := fake.translatePathReturnsOnCall[len(fake.translatePathArgsForCall)]
	fake.translatePathArgsForCall = append(fake.translatePathArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.TranslatePathStub
	fakeReturns := fake.translatePathReturns
	fake.recordInvocation("TranslatePath", []interface{}{arg1})
	fake.translatePathMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Config) TranslatePathCallCount() int {
	fake.translatePathMutex.RLock()
	defer fake.translatePathMutex.RUnlock()
	return len(fake.translatePathArgsForCall)
}

func (fake *Config) TranslatePathCalls(stub func(string) string) {
	fake.translatePathMutex.Lock()
	defer fake.translatePathMutex.Unlock()
	fake.TranslatePathStub = stub
}

func (fake *Config) TranslatePathArgsForCall(i int) string {
	fake.translatePathMutex.RLock()
	defer fake.translatePathMutex.RUnlock()
	argsForCall := fake.translatePathArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Config) TranslatePathReturns(result1 string) {
	fake.translatePathMutex.Lock()
	defer fake.translatePathMutex.Unlock()
	fake.TranslatePathStub = nil
	fake.translatePathReturns = struct {
		result1 string
	}{result1}
}

func (fake *Config) TranslatePathReturnsOnCall(i int, result1 string) {
	fake.translatePathMutex.Lock()
	defer fake.translatePathMutex.Unlock()
	fake.TranslatePathStub = nil
	if fake.translatePathReturnsOnCall == nil {
		fake.translatePathReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.translatePathReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *Config) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Config) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ membership.Config = new(Config)
