// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/driver"
	drivera "github.com/hyperledger-labs/fabric-token-sdk/token/services/identity/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/identity/membership"
)

type IdentityProvider struct {
	BindStub        func(context.Context, driver.Identity, ...driver.Identity) error
	bindMutex       sync.RWMutex
	bindArgsForCall []struct {
		arg1 context.Context
		arg2 driver.Identity
		arg3 []driver.Identity
	}
	bindReturns struct {
		result1 error
	}
	bindReturnsOnCall map[int]struct {
		result1 error
	}
	IsMeStub        func(context.Context, driver.Identity) bool
	isMeMutex       sync.RWMutex
	isMeArgsForCall []struct {
		arg1 context.Context
		arg2 driver.Identity
	}
	isMeReturns struct {
		result1 bool
	}
	isMeReturnsOnCall map[int]struct {
		result1 bool
	}
	RegisterIdentityDescriptorStub        func(context.Context, *drivera.IdentityDescriptor, driver.Identity) error
	registerIdentityDescriptorMutex       sync.RWMutex
	registerIdentityDescriptorArgsForCall []struct {
		arg1 context.Context
		arg2 *drivera.IdentityDescriptor
		arg3 driver.Identity
	}
	registerIdentityDescriptorReturns struct {
		result1 error
	}
	registerIdentityDescriptorReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *IdentityProvider) Bind(arg1 context.Context, arg2 driver.Identity, arg3 ...driver.Identity) error {
	fake.bindMutex.Lock()
	ret, specificReturn := fake.bindReturnsOnCall[len(fake.bindArgsForCall)]
	fake.bindArgsForCall = append(fake.bindArgsForCall, struct {
		arg1 context.Context
		arg2 driver.Identity
		arg3 []driver.Identity
	}{arg1, arg2, arg3})
	stub := fake.BindStub
	fakeReturns := fake.bindReturns
	fake.recordInvocation("Bind", []interface{}{arg1, arg2, arg3})
	fake.bindMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IdentityProvider) BindCallCount() int {
	fake.bindMutex.RLock()
	defer fake.bindMutex.RUnlock()
	return len(fake.bindArgsForCall)
}

func (fake *IdentityProvider) BindCalls(stub func(context.Context, driver.Identity, ...driver.Identity) error) {
	fake.bindMutex.Lock()
	defer fake.bindMutex.Unlock()
	fake.BindStub = stub
}

func (fake *IdentityProvider) BindArgsForCall(i int) (context.Context, driver.Identity, []driver.Identity) {
	fake.bindMutex.RLock()
	defer fake.bindMutex.RUnlock()
	argsForCall := fake.bindArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *IdentityProvider) BindReturns(result1 error) {
	fake.bindMutex.Lock()
	defer fake.bindMutex.Unlock()
	fake.BindStub = nil
	fake.bindReturns = struct {
		result1 error
	}{result1}
}

func (fake *IdentityProvider) BindReturnsOnCall(i int, result1 error) {
	fake.bindMutex.Lock()
	defer fake.bindMutex.Unlock()
	fake.BindStub = nil
	if fake.bindReturnsOnCall == nil {
		fake.bindReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.bindReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *IdentityProvider) IsMe(arg1 context.Context, arg2 driver.Identity) bool {
	fake.isMeMutex.Lock()
	ret, specificReturn := fake.isMeReturnsOnCall[len(fake.isMeArgsForCall)]
	fake.isMeArgsForCall = append(fake.isMeArgsForCall, struct {
		arg1 context.Context
		arg2 driver.Identity
	}{arg1, arg2})
	stub := fake.IsMeStub
	fakeReturns := fake.isMeReturns
	fake.recordInvocation("IsMe", []interface{}{arg1, arg2})
	fake.isMeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IdentityProvider) IsMeCallCount() int {
	fake.isMeMutex.RLock()
	defer fake.isMeMutex.RUnlock()
	return len(fake.isMeArgsForCall)
}

func (fake *IdentityProvider) IsMeCalls(stub func(context.Context, driver.Identity) bool) {
	fake.isMeMutex.Lock()
	defer fake.isMeMutex.Unlock()
	fake.IsMeStub = stub
}

func (fake *IdentityProvider) IsMeArgsForCall(i int) (context.Context, driver.Identity) {
	fake.isMeMutex.RLock()
	defer fake.isMeMutex.RUnlock()
	argsForCall := fake.isMeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IdentityProvider) IsMeReturns(result1 bool) {
	fake.isMeMutex.Lock()
	defer fake.isMeMutex.Unlock()
	fake.IsMeStub = nil
	fake.isMeReturns = struct {
		result1 bool
	}{result1}
}

func (fake *IdentityProvider) IsMeReturnsOnCall(i int, result1 bool) {
	fake.isMeMutex.Lock()
	defer fake.isMeMutex.Unlock()
	fake.IsMeStub = nil
	if fake.isMeReturnsOnCall == nil {
		fake.isMeReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isMeReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *IdentityProvider) RegisterIdentityDescriptor(arg1 context.Context, arg2 *drivera.IdentityDescriptor, arg3 driver.Identity) error {
	fake.registerIdentityDescriptorMutex.Lock()
	ret, specificReturn := fake.registerIdentityDescriptorReturnsOnCall[len(fake.registerIdentityDescriptorArgsForCall)]
	fake.registerIdentityDescriptorArgsForCall = append(fake.registerIdentityDescriptorArgsForCall, struct {
		arg1 context.Context
		arg2 *drivera.IdentityDescriptor
		arg3 driver.Identity
	}{arg1, arg2, arg3})
	stub := fake.RegisterIdentityDescriptorStub
	fakeReturns := fake.registerIdentityDescriptorReturns
	fake.recordInvocation("RegisterIdentityDescriptor", []interface{}{arg1, arg2, arg3})
	fake.registerIdentityDescriptorMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IdentityProvider) RegisterIdentityDescriptorCallCount() int {
	fake.registerIdentityDescriptorMutex.RLock()
	defer fake.registerIdentityDescriptorMutex.RUnlock()
	return len(fake.registerIdentityDescriptorArgsForCall)
}

func (fake *IdentityProvider) RegisterIdentityDescriptorCalls(stub func(context.Context, *drivera.IdentityDescriptor, driver.Identity) error) {
	fake.registerIdentityDescriptorMutex.Lock()
	defer fake.registerIdentityDescriptorMutex.Unlock()
	fake.RegisterIdentityDescriptorStub = stub
}

func (fake *IdentityProvider) RegisterIdentityDescriptorArgsForCall(i int) (context.Context, *drivera.IdentityDescriptor, driver.Identity) {
	fake.registerIdentityDescriptorMutex.RLock()
	defer fake.registerIdentityDescriptorMutex.RUnlock()
	argsForCall := fake.registerIdentityDescriptorArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *IdentityProvider) RegisterIdentityDescriptorReturns(result1 error) {
	fake.registerIdentityDescriptorMutex.Lock()
	defer fake.registerIdentityDescriptorMutex.Unlock()
	fake.RegisterIdentityDescriptorStub = nil
	fake.registerIdentityDescriptorReturns = struct {
		result1 error
	}{result1}
}

func (fake *IdentityProvider) RegisterIdentityDescriptorReturnsOnCall(i int, result1 error) {
	fake.registerIdentityDescriptorMutex.Lock()
	defer fake.registerIdentityDescriptorMutex.Unlock()
	fake.RegisterIdentityDescriptorStub = nil
	if fake.registerIdentityDescriptorReturnsOnCall == nil {
		fake.registerIdentityDescriptorReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.registerIdentityDescriptorReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *IdentityProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *IdentityProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ membership.IdentityProvider = new(IdentityProvider)
