// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/services/identity/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/identity/membership"
)

type IdentityStoreService struct {
	AddConfigurationStub        func(context.Context, driver.IdentityConfiguration) error
	addConfigurationMutex       sync.RWMutex
	addConfigurationArgsForCall []struct {
		arg1 context.Context
		arg2 driver.IdentityConfiguration
	}
	addConfigurationReturns struct {
		result1 error
	}
	addConfigurationReturnsOnCall map[int]struct {
		result1 error
	}
	ConfigurationExistsStub        func(context.Context, string, string, string) (bool, error)
	configurationExistsMutex       sync.RWMutex
	configurationExistsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	configurationExistsReturns struct {
		result1 bool
		result2 error
	}
	configurationExistsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	GetConfigurationStub        func(context.Context, string, string, string) (*driver.IdentityConfiguration, error)
	getConfigurationMutex       sync.RWMutex
	getConfigurationArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	getConfigurationReturns struct {
		result1 *driver.IdentityConfiguration
		result2 error
	}
	getConfigurationReturnsOnCall map[int]struct {
		result1 *driver.IdentityConfiguration
		result2 error
	}
	IteratorConfigurationsStub        func(context.Context, string) (membership.IdentityConfigurationIterator, error)
	iteratorConfigurationsMutex       sync.RWMutex
	iteratorConfigurationsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	iteratorConfigurationsReturns struct {
		result1 membership.IdentityConfigurationIterator
		result2 error
	}
	iteratorConfigurationsReturnsOnCall map[int]struct {
		result1 membership.IdentityConfigurationIterator
		result2 error
	}
	NotifierStub        func() (driver.IdentityNotifier, error)
	notifierMutex       sync.RWMutex
	notifierArgsForCall []struct {
	}
	notifierReturns struct {
		result1 driver.IdentityNotifier
		result2 error
	}
	notifierReturnsOnCall map[int]struct {
		result1 driver.IdentityNotifier
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *IdentityStoreService) AddConfiguration(arg1 context.Context, arg2 driver.IdentityConfiguration) error {
	fake.addConfigurationMutex.Lock()
	ret, specificReturn := fake.addConfigurationReturnsOnCall[len(fake.addConfigurationArgsForCall)]
	fake.addConfigurationArgsForCall = append(fake.addConfigurationArgsForCall, struct {
		arg1 context.Context
		arg2 driver.IdentityConfiguration
	}{arg1, arg2})
	stub := fake.AddConfigurationStub
	fakeReturns := fake.addConfigurationReturns
	fake.recordInvocation("AddConfiguration", []interface{}{arg1, arg2})
	fake.addConfigurationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IdentityStoreService) AddConfigurationCallCount() int {
	fake.addConfigurationMutex.RLock()
	defer fake.addConfigurationMutex.RUnlock()
	return len(fake.addConfigurationArgsForCall)
}

func (fake *IdentityStoreService) AddConfigurationCalls(stub func(context.Context, driver.IdentityConfiguration) error) {
	fake.addConfigurationMutex.Lock()
	defer fake.addConfigurationMutex.Unlock()
	fake.AddConfigurationStub = stub
}

func (fake *IdentityStoreService) AddConfigurationArgsForCall(i int) (context.Context, driver.IdentityConfiguration) {
	fake.addConfigurationMutex.RLock()
	defer fake.addConfigurationMutex.RUnlock()
	argsForCall := fake.addConfigurationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IdentityStoreService) AddConfigurationReturns(result1 error) {
	fake.addConfigurationMutex.Lock()
	defer fake.addConfigurationMutex.Unlock()
	fake.AddConfigurationStub = nil
	fake.addConfigurationReturns = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) AddConfigurationReturnsOnCall(i int, result1 error) {
	fake.addConfigurationMutex.Lock()
	defer fake.addConfigurationMutex.Unlock()
	fake.AddConfigurationStub = nil
	if fake.addConfigurationReturnsOnCall == nil {
		fake.addConfigurationReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addConfigurationReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) ConfigurationExists(arg1 context.Context, arg2 string, arg3 string, arg4 string) (bool, error) {
	fake.configurationExistsMutex.Lock()
	ret, specificReturn := fake.configurationExistsReturnsOnCall[len(fake.configurationExistsArgsForCall)]
	fake.configurationExistsArgsForCall = append(fake.configurationExistsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.ConfigurationExistsStub
	fakeReturns := fake.configurationExistsReturns
	fake.recordInvocation("ConfigurationExists", []interface{}{arg1, arg2, arg3, arg4})
	fake.configurationExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IdentityStoreService) ConfigurationExistsCallCount() int {
	fake.configurationExistsMutex.RLock()
	defer fake.configurationExistsMutex.RUnlock()
	return len(fake.configurationExistsArgsForCall)
}

func (fake *IdentityStoreService) ConfigurationExistsCalls(stub func(context.Context, string, string, string) (bool, error)) {
	fake.configurationExistsMutex.Lock()
	defer fake.configurationExistsMutex.Unlock()
	fake.ConfigurationExistsStub = stub
}

func (fake *IdentityStoreService) ConfigurationExistsArgsForCall(i int) (context.Context, string, string, string) {
	fake.configurationExistsMutex.RLock()
	defer fake.configurationExistsMutex.RUnlock()
	argsForCall := fake.configurationExistsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *IdentityStoreService) ConfigurationExistsReturns(result1 bool, result2 error) {
	fake.configurationExistsMutex.Lock()
	defer fake.configurationExistsMutex.Unlock()
	fake.ConfigurationExistsStub = nil
	fake.configurationExistsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) ConfigurationExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.configurationExistsMutex.Lock()
	defer fake.configurationExistsMutex.Unlock()
	fake.ConfigurationExistsStub = nil
	if fake.configurationExistsReturnsOnCall == nil {
		fake.configurationExistsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.configurationExistsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) GetConfiguration(arg1 context.Context, arg2 string, arg3 string, arg4 string) (*driver.IdentityConfiguration, error) {
	fake.getConfigurationMutex.Lock()
	ret, specificReturn := fake.getConfigurationReturnsOnCall[len(fake.getConfigurationArgsForCall)]
	fake.getConfigurationArgsForCall = append(fake.getConfigurationArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetConfigurationStub
	fakeReturns := fake.getConfigurationReturns
	fake.recordInvocation("GetConfiguration", []interface{}{arg1, arg2, arg3, arg4})
	fake.getConfigurationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IdentityStoreService) GetConfigurationCallCount() int {
	fake.getConfigurationMutex.RLock()
	defer fake.getConfigurationMutex.RUnlock()
	return len(fake.getConfigurationArgsForCall)
}

func (fake *IdentityStoreService) GetConfigurationCalls(stub func(context.Context, string, string, string) (*driver.IdentityConfiguration, error)) {
	fake.getConfigurationMutex.Lock()
	defer fake.getConfigurationMutex.Unlock()
	fake.GetConfigurationStub = stub
}

func (fake *IdentityStoreService) GetConfigurationArgsForCall(i int) (context.Context, string, string, string) {
	fake.getConfigurationMutex.RLock()
	defer fake.getConfigurationMutex.RUnlock()
	argsForCall := fake.getConfigurationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *IdentityStoreService) GetConfigurationReturns(result1 *driver.IdentityConfiguration, result2 error) {
	fake.getConfigurationMutex.Lock()
	defer fake.getConfigurationMutex.Unlock()
	fake.GetConfigurationStub = nil
	fake.getConfigurationReturns = struct {
		result1 *driver.IdentityConfiguration
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) GetConfigurationReturnsOnCall(i int, result1 *driver.IdentityConfiguration, result2 error) {
	fake.getConfigurationMutex.Lock()
	defer fake.getConfigurationMutex.Unlock()
	fake.GetConfigurationStub = nil
	if fake.getConfigurationReturnsOnCall == nil {
		fake.getConfigurationReturnsOnCall = make(map[int]struct {
			result1 *driver.IdentityConfiguration
			result2 error
		})
	}
	fake.getConfigurationReturnsOnCall[i] = struct {
		result1 *driver.IdentityConfiguration
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) IteratorConfigurations(arg1 context.Context, arg2 string) (membership.IdentityConfigurationIterator, error) {
	fake.iteratorConfigurationsMutex.Lock()
	ret, specificReturn := fake.iteratorConfigurationsReturnsOnCall[len(fake.iteratorConfigurationsArgsForCall)]
	fake.iteratorConfigurationsArgsForCall = append(fake.iteratorConfigurationsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.IteratorConfigurationsStub
	fakeReturns := fake.iteratorConfigurationsReturns
	fake.recordInvocation("IteratorConfigurations", []interface{}{arg1, arg2})
	fake.iteratorConfigurationsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IdentityStoreService) IteratorConfigurationsCallCount() int {
	fake.iteratorConfigurationsMutex.RLock()
	defer fake.iteratorConfigurationsMutex.RUnlock()
	return len(fake.iteratorConfigurationsArgsForCall)
}

func (fake *IdentityStoreService) IteratorConfigurationsCalls(stub func(context.Context, string) (membership.IdentityConfigurationIterator, error)) {
	fake.iteratorConfigurationsMutex.Lock()
	defer fake.iteratorConfigurationsMutex.Unlock()
	fake.IteratorConfigurationsStub = stub
}

func (fake *IdentityStoreService) IteratorConfigurationsArgsForCall(i int) (context.Context, string) {
	fake.iteratorConfigurationsMutex.RLock()
	defer fake.iteratorConfigurationsMutex.RUnlock()
	argsForCall := fake.iteratorConfigurationsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IdentityStoreService) IteratorConfigurationsReturns(result1 membership.IdentityConfigurationIterator, result2 error) {
	fake.iteratorConfigurationsMutex.Lock()
	defer fake.iteratorConfigurationsMutex.Unlock()
	fake.IteratorConfigurationsStub = nil
	fake.iteratorConfigurationsReturns = struct {
		result1 membership.IdentityConfigurationIterator
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) IteratorConfigurationsReturnsOnCall(i int, result1 membership.IdentityConfigurationIterator, result2 error) {
	fake.iteratorConfigurationsMutex.Lock()
	defer fake.iteratorConfigurationsMutex.Unlock()
	fake.IteratorConfigurationsStub = nil
	if fake.iteratorConfigurationsReturnsOnCall == nil {
		fake.iteratorConfigurationsReturnsOnCall = make(map[int]struct {
			result1 membership.IdentityConfigurationIterator
			result2 error
		})
	}
	fake.iteratorConfigurationsReturnsOnCall[i] = struct {
		result1 membership.IdentityConfigurationIterator
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) Notifier() (driver.IdentityNotifier, error) {
	fake.notifierMutex.Lock()
	ret, specificReturn := fake.notifierReturnsOnCall[len(fake.notifierArgsForCall)]
	fake.notifierArgsForCall = append(fake.notifierArgsForCall, struct {
	}{})
	stub := fake.NotifierStub
	fakeReturns := fake.notifierReturns
	fake.recordInvocation("Notifier", []interface{}{})
	fake.notifierMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IdentityStoreService) NotifierCallCount() int {
	fake.notifierMutex.RLock()
	defer fake.notifierMutex.RUnlock()
	return len(fake.notifierArgsForCall)
}

func (fake *IdentityStoreService) NotifierCalls(stub func() (driver.IdentityNotifier, error)) {
	fake.notifierMutex.Lock()
	defer fake.notifierMutex.Unlock()
	fake.NotifierStub = stub
}

func (fake *IdentityStoreService) NotifierReturns(result1 driver.IdentityNotifier, result2 error) {
	fake.notifierMutex.Lock()
	defer fake.notifierMutex.Unlock()
	fake.NotifierStub = nil
	fake.notifierReturns = struct {
		result1 driver.IdentityNotifier
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) NotifierReturnsOnCall(i int, result1 driver.IdentityNotifier, result2 error) {
	fake.notifierMutex.Lock()
	defer fake.notifierMutex.Unlock()
	fake.NotifierStub = nil
	if fake.notifierReturnsOnCall == nil {
		fake.notifierReturnsOnCall = make(map[int]struct {
			result1 driver.IdentityNotifier
			result2 error
		})
	}
	fake.notifierReturnsOnCall[i] = struct {
		result1 driver.IdentityNotifier
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *IdentityStoreService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ membership.IdentityStoreService = new(IdentityStoreService)
