// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/token"
)

type IssueService struct {
	DeserializeIssueActionStub        func([]byte) (driver.IssueAction, error)
	deserializeIssueActionMutex       sync.RWMutex
	deserializeIssueActionArgsForCall []struct {
		arg1 []byte
	}
	deserializeIssueActionReturns struct {
		result1 driver.IssueAction
		result2 error
	}
	deserializeIssueActionReturnsOnCall map[int]struct {
		result1 driver.IssueAction
		result2 error
	}
	IssueStub        func(context.Context, driver.Identity, token.Type, []uint64, [][]byte, *driver.IssueOptions) (driver.IssueAction, *driver.IssueMetadata, error)
	issueMutex       sync.RWMutex
	issueArgsForCall []struct {
		arg1 context.Context
		arg2 driver.Identity
		arg3 token.Type
		arg4 []uint64
		arg5 [][]byte
		arg6 *driver.IssueOptions
	}
	issueReturns struct {
		result1 driver.IssueAction
		result2 *driver.IssueMetadata
		result3 error
	}
	issueReturnsOnCall map[int]struct {
		result1 driver.IssueAction
		result2 *driver.IssueMetadata
		result3 error
	}
	VerifyIssueStub        func(context.Context, driver.IssueAction, []*driver.IssueOutputMetadata) error
	verifyIssueMutex       sync.RWMutex
	verifyIssueArgsForCall []struct {
		arg1 context.Context
		arg2 driver.IssueAction
		arg3 []*driver.IssueOutputMetadata
	}
	verifyIssueReturns struct {
		result1 error
	}
	verifyIssueReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *IssueService) DeserializeIssueAction(arg1 []byte) (driver.IssueAction, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.deserializeIssueActionMutex.Lock()
	ret, specificReturn := fake.deserializeIssueActionReturnsOnCall[len(fake.deserializeIssueActionArgsForCall)]
	fake.deserializeIssueActionArgsForCall = append(fake.deserializeIssueActionArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.DeserializeIssueActionStub
	fakeReturns := fake.deserializeIssueActionReturns
	fake.recordInvocation("DeserializeIssueAction", []interface{}{arg1Copy})
	fake.deserializeIssueActionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IssueService) DeserializeIssueActionCallCount() int {
	fake.deserializeIssueActionMutex.RLock()
	defer fake.deserializeIssueActionMutex.RUnlock()
	return len(fake.deserializeIssueActionArgsForCall)
}

func (fake *IssueService) DeserializeIssueActionCalls(stub func([]byte) (driver.IssueAction, error)) {
	fake.deserializeIssueActionMutex.Lock()
	defer fake.deserializeIssueActionMutex.Unlock()
	fake.DeserializeIssueActionStub = stub
}

func (fake *IssueService) DeserializeIssueActionArgsForCall(i int) []byte {
	fake.deserializeIssueActionMutex.RLock()
	defer fake.deserializeIssueActionMutex.RUnlock()
	argsForCall := fake.deserializeIssueActionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *IssueService) DeserializeIssueActionReturns(result1 driver.IssueAction, result2 error) {
	fake.deserializeIssueActionMutex.Lock()
	defer fake.deserializeIssueActionMutex.Unlock()
	fake.DeserializeIssueActionStub = nil
	fake.deserializeIssueActionReturns = struct {
		result1 driver.IssueAction
		result2 error
	}{result1, result2}
}

func (fake *IssueService) DeserializeIssueActionReturnsOnCall(i int, result1 driver.IssueAction, result2 error) {
	fake.deserializeIssueActionMutex.Lock()
	defer fake.deserializeIssueActionMutex.Unlock()
	fake.DeserializeIssueActionStub = nil
	if fake.deserializeIssueActionReturnsOnCall == nil {
		fake.deserializeIssueActionReturnsOnCall = make(map[int]struct {
			result1 driver.IssueAction
			result2 error
		})
	}
	fake.deserializeIssueActionReturnsOnCall[i] = struct {
		result1 driver.IssueAction
		result2 error
	}{result1, result2}
}

func (fake *IssueService) Issue(arg1 context.Context, arg2 driver.Identity, arg3 token.Type, arg4 []uint64, arg5 [][]byte, arg6 *driver.IssueOptions) (driver.IssueAction, *driver.IssueMetadata, error) {
	var arg4Copy []uint64
	if arg4 != nil {
		arg4Copy = make([]uint64, len(arg4))
		copy(arg4Copy, arg4)
	}
	var arg5Copy [][]byte
	if arg5 != nil {
		arg5Copy = make([][]byte, len(arg5))
		copy(arg5Copy, arg5)
	}
	fake.issueMutex.Lock()
	ret, specificReturn := fake.issueReturnsOnCall[len(fake.issueArgsForCall)]
	fake.issueArgsForCall = append(fake.issueArgsForCall, struct {
		arg1 context.Context
		arg2 driver.Identity
		arg3 token.Type
		arg4 []uint64
		arg5 [][]byte
		arg6 *driver.IssueOptions
	}{arg1, arg2, arg3, arg4Copy, arg5Copy, arg6})
	stub := fake.IssueStub
	fakeReturns := fake.issueReturns
	fake.recordInvocation("Issue", []interface{}{arg1, arg2, arg3, arg4Copy, arg5Copy, arg6})
	fake.issueMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *IssueService) IssueCallCount() int {
	fake.issueMutex.RLock()
	defer fake.issueMutex.RUnlock()
	return len(fake.issueArgsForCall)
}

func (fake *IssueService) IssueCalls(stub func(context.Context, driver.Identity, token.Type, []uint64, [][]byte, *driver.IssueOptions) (driver.IssueAction, *driver.IssueMetadata, error)) {
	fake.issueMutex.Lock()
	defer fake.issueMutex.Unlock()
	fake.IssueStub = stub
}

func (fake *IssueService) IssueArgsForCall(i int) (context.Context, driver.Identity, token.Type, []uint64, [][]byte, *driver.IssueOptions) {
	fake.issueMutex.RLock()
	defer fake.issueMutex.RUnlock()
	argsForCall := fake.issueArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *IssueService) IssueReturns(result1 driver.IssueAction, result2 *driver.IssueMetadata, result3 error) {
	fake.issueMutex.Lock()
	defer fake.issueMutex.Unlock()
	fake.IssueStub = nil
	fake.issueReturns = struct {
		result1 driver.IssueAction
		result2 *driver.IssueMetadata
		result3 error
	}{result1, result2, result3}
}

func (fake *IssueService) IssueReturnsOnCall(i int, result1 driver.IssueAction, result2 *driver.IssueMetadata, result3 error) {
	fake.issueMutex.Lock()
	defer fake.issueMutex.Unlock()
	fake.IssueStub = nil
	if fake.issueReturnsOnCall == nil {
		fake.issueReturnsOnCall = make(map[int]struct {
			result1 driver.IssueAction
			result2 *driver.IssueMetadata
			result3 error
		})
	}
	fake.issueReturnsOnCall[i] = struct {
		result1 driver.IssueAction
		result2 *driver.IssueMetadata
		result3 error
	}{result1, result2, result3}
}

func (fake *IssueService) VerifyIssue(arg1 context.Context, arg2 driver.IssueAction, arg3 []*driver.IssueOutputMetadata) error {
	var arg3Copy []*driver.IssueOutputMetadata
	if arg3 != nil {
		arg3Copy = make([]*driver.IssueOutputMetadata, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.verifyIssueMutex.Lock()
	ret, specificReturn := fake.verifyIssueReturnsOnCall[len(fake.verifyIssueArgsForCall)]
	fake.verifyIssueArgsForCall = append(fake.verifyIssueArgsForCall, struct {
		arg1 context.Context
		arg2 driver.IssueAction
		arg3 []*driver.IssueOutputMetadata
	}{arg1, arg2, arg3Copy})
	stub := fake.VerifyIssueStub
	fakeReturns := fake.verifyIssueReturns
	fake.recordInvocation("VerifyIssue", []interface{}{arg1, arg2, arg3Copy})
	fake.verifyIssueMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IssueService) VerifyIssueCallCount() int {
	fake.verifyIssueMutex.RLock()
	defer fake.verifyIssueMutex.RUnlock()
	return len(fake.verifyIssueArgsForCall)
}

func (fake *IssueService) VerifyIssueCalls(stub func(context.Context, driver.IssueAction, []*driver.IssueOutputMetadata) error) {
	fake.verifyIssueMutex.Lock()
	defer fake.verifyIssueMutex.Unlock()
	fake.VerifyIssueStub = stub
}

func (fake *IssueService) VerifyIssueArgsForCall(i int) (context.Context, driver.IssueAction, []*driver.IssueOutputMetadata) {
	fake.verifyIssueMutex.RLock()
	defer fake.verifyIssueMutex.RUnlock()
	argsForCall := fake.verifyIssueArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *IssueService) VerifyIssueReturns(result1 error) {
	fake.verifyIssueMutex.Lock()
	defer fake.verifyIssueMutex.Unlock()
	fake.VerifyIssueStub = nil
	fake.verifyIssueReturns = struct {
		result1 error
	}{result1}
}

func (fake *IssueService) VerifyIssueReturnsOnCall(i int, result1 error) {
	fake.verifyIssueMutex.Lock()
	defer fake.verifyIssueMutex.Unlock()
	fake.VerifyIssueStub = nil
	if fake.verifyIssueReturnsOnCall == nil {
		fake.verifyIssueReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyIssueReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *IssueService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *IssueService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.IssueService = new(IssueService)
