// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/driver"
)

type LedgerToken struct {
	GetOwnerStub        func() []byte
	getOwnerMutex       sync.RWMutex
	getOwnerArgsForCall []struct {
	}
	getOwnerReturns struct {
		result1 []byte
	}
	getOwnerReturnsOnCall map[int]struct {
		result1 []byte
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *LedgerToken) GetOwner() []byte {
	fake.getOwnerMutex.Lock()
	ret, specificReturn := fake.getOwnerReturnsOnCall[len(fake.getOwnerArgsForCall)]
	fake.getOwnerArgsForCall = append(fake.getOwnerArgsForCall, struct {
	}{})
	stub := fake.GetOwnerStub
	fakeReturns := fake.getOwnerReturns
	fake.recordInvocation("GetOwner", []interface{}{})
	fake.getOwnerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *LedgerToken) GetOwnerCallCount() int {
	fake.getOwnerMutex.RLock()
	defer fake.getOwnerMutex.RUnlock()
	return len(fake.getOwnerArgsForCall)
}

func (fake *LedgerToken) GetOwnerCalls(stub func() []byte) {
	fake.getOwnerMutex.Lock()
	defer fake.getOwnerMutex.Unlock()
	fake.GetOwnerStub = stub
}

func (fake *LedgerToken) GetOwnerReturns(result1 []byte) {
	fake.getOwnerMutex.Lock()
	defer fake.getOwnerMutex.Unlock()
	fake.GetOwnerStub = nil
	fake.getOwnerReturns = struct {
		result1 []byte
	}{result1}
}

func (fake *LedgerToken) GetOwnerReturnsOnCall(i int, result1 []byte) {
	fake.getOwnerMutex.Lock()
	defer fake.getOwnerMutex.Unlock()
	fake.GetOwnerStub = nil
	if fake.getOwnerReturnsOnCall == nil {
		fake.getOwnerReturnsOnCall = make(map[int]struct {
			result1 []byte
		})
	}
	fake.getOwnerReturnsOnCall[i] = struct {
		result1 []byte
	}{result1}
}

func (fake *LedgerToken) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *LedgerToken) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.LedgerToken = new(LedgerToken)
