// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/driver"
)

type MetadataDeserializer[M any] struct {
	DeserializeMetadataStub        func([]byte) (M, error)
	deserializeMetadataMutex       sync.RWMutex
	deserializeMetadataArgsForCall []struct {
		arg1 []byte
	}
	deserializeMetadataReturns struct {
		result1 M
		result2 error
	}
	deserializeMetadataReturnsOnCall map[int]struct {
		result1 M
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *MetadataDeserializer[M]) DeserializeMetadata(arg1 []byte) (M, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.deserializeMetadataMutex.Lock()
	ret, specificReturn := fake.deserializeMetadataReturnsOnCall[len(fake.deserializeMetadataArgsForCall)]
	fake.deserializeMetadataArgsForCall = append(fake.deserializeMetadataArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.DeserializeMetadataStub
	fakeReturns := fake.deserializeMetadataReturns
	fake.recordInvocation("DeserializeMetadata", []interface{}{arg1Copy})
	fake.deserializeMetadataMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MetadataDeserializer[M]) DeserializeMetadataCallCount() int {
	fake.deserializeMetadataMutex.RLock()
	defer fake.deserializeMetadataMutex.RUnlock()
	return len(fake.deserializeMetadataArgsForCall)
}

func (fake *MetadataDeserializer[M]) DeserializeMetadataCalls(stub func([]byte) (M, error)) {
	fake.deserializeMetadataMutex.Lock()
	defer fake.deserializeMetadataMutex.Unlock()
	fake.DeserializeMetadataStub = stub
}

func (fake *MetadataDeserializer[M]) DeserializeMetadataArgsForCall(i int) []byte {
	fake.deserializeMetadataMutex.RLock()
	defer fake.deserializeMetadataMutex.RUnlock()
	argsForCall := fake.deserializeMetadataArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MetadataDeserializer[M]) DeserializeMetadataReturns(result1 M, result2 error) {
	fake.deserializeMetadataMutex.Lock()
	defer fake.deserializeMetadataMutex.Unlock()
	fake.DeserializeMetadataStub = nil
	fake.deserializeMetadataReturns = struct {
		result1 M
		result2 error
	}{result1, result2}
}

func (fake *MetadataDeserializer[M]) DeserializeMetadataReturnsOnCall(i int, result1 M, result2 error) {
	fake.deserializeMetadataMutex.Lock()
	defer fake.deserializeMetadataMutex.Unlock()
	fake.DeserializeMetadataStub = nil
	if fake.deserializeMetadataReturnsOnCall == nil {
		fake.deserializeMetadataReturnsOnCall = make(map[int]struct {
			result1 M
			result2 error
		})
	}
	fake.deserializeMetadataReturnsOnCall[i] = struct {
		result1 M
		result2 error
	}{result1, result2}
}

func (fake *MetadataDeserializer[M]) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MetadataDeserializer[M]) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.MetadataDeserializer[any] = new(MetadataDeserializer[any])
