// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/driver"
)

type PPMFactory struct {
	NewPublicParametersManagerStub        func(driver.PublicParameters) (driver.PublicParamsManager, error)
	newPublicParametersManagerMutex       sync.RWMutex
	newPublicParametersManagerArgsForCall []struct {
		arg1 driver.PublicParameters
	}
	newPublicParametersManagerReturns struct {
		result1 driver.PublicParamsManager
		result2 error
	}
	newPublicParametersManagerReturnsOnCall map[int]struct {
		result1 driver.PublicParamsManager
		result2 error
	}
	NewValidatorStub        func(driver.PublicParameters) (driver.Validator, error)
	newValidatorMutex       sync.RWMutex
	newValidatorArgsForCall []struct {
		arg1 driver.PublicParameters
	}
	newValidatorReturns struct {
		result1 driver.Validator
		result2 error
	}
	newValidatorReturnsOnCall map[int]struct {
		result1 driver.Validator
		result2 error
	}
	PublicParametersFromBytesStub        func([]byte) (driver.PublicParameters, error)
	publicParametersFromBytesMutex       sync.RWMutex
	publicParametersFromBytesArgsForCall []struct {
		arg1 []byte
	}
	publicParametersFromBytesReturns struct {
		result1 driver.PublicParameters
		result2 error
	}
	publicParametersFromBytesReturnsOnCall map[int]struct {
		result1 driver.PublicParameters
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PPMFactory) NewPublicParametersManager(arg1 driver.PublicParameters) (driver.PublicParamsManager, error) {
	fake.newPublicParametersManagerMutex.Lock()
	ret, specificReturn := fake.newPublicParametersManagerReturnsOnCall[len(fake.newPublicParametersManagerArgsForCall)]
	fake.newPublicParametersManagerArgsForCall = append(fake.newPublicParametersManagerArgsForCall, struct {
		arg1 driver.PublicParameters
	}{arg1})
	stub := fake.NewPublicParametersManagerStub
	fakeReturns := fake.newPublicParametersManagerReturns
	fake.recordInvocation("NewPublicParametersManager", []interface{}{arg1})
	fake.newPublicParametersManagerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PPMFactory) NewPublicParametersManagerCallCount() int {
	fake.newPublicParametersManagerMutex.RLock()
	defer fake.newPublicParametersManagerMutex.RUnlock()
	return len(fake.newPublicParametersManagerArgsForCall)
}

func (fake *PPMFactory) NewPublicParametersManagerCalls(stub func(driver.PublicParameters) (driver.PublicParamsManager, error)) {
	fake.newPublicParametersManagerMutex.Lock()
	defer fake.newPublicParametersManagerMutex.Unlock()
	fake.NewPublicParametersManagerStub = stub
}

func (fake *PPMFactory) NewPublicParametersManagerArgsForCall(i int) driver.PublicParameters {
	fake.newPublicParametersManagerMutex.RLock()
	defer fake.newPublicParametersManagerMutex.RUnlock()
	argsForCall := fake.newPublicParametersManagerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PPMFactory) NewPublicParametersManagerReturns(result1 driver.PublicParamsManager, result2 error) {
	fake.newPublicParametersManagerMutex.Lock()
	defer fake.newPublicParametersManagerMutex.Unlock()
	fake.NewPublicParametersManagerStub = nil
	fake.newPublicParametersManagerReturns = struct {
		result1 driver.PublicParamsManager
		result2 error
	}{result1, result2}
}

func (fake *PPMFactory) NewPublicParametersManagerReturnsOnCall(i int, result1 driver.PublicParamsManager, result2 error) {
	fake.newPublicParametersManagerMutex.Lock()
	defer fake.newPublicParametersManagerMutex.Unlock()
	fake.NewPublicParametersManagerStub = nil
	if fake.newPublicParametersManagerReturnsOnCall == nil {
		fake.newPublicParametersManagerReturnsOnCall = make(map[int]struct {
			result1 driver.PublicParamsManager
			result2 error
		})
	}
	fake.newPublicParametersManagerReturnsOnCall[i] = struct {
		result1 driver.PublicParamsManager
		result2 error
	}{result1, result2}
}

func (fake *PPMFactory) NewValidator(arg1 driver.PublicParameters) (driver.Validator, error) {
	fake.newValidatorMutex.Lock()
	ret, specificReturn := fake.newValidatorReturnsOnCall[len(fake.newValidatorArgsForCall)]
	fake.newValidatorArgsForCall = append(fake.newValidatorArgsForCall, struct {
		arg1 driver.PublicParameters
	}{arg1})
	stub := fake.NewValidatorStub
	fakeReturns := fake.newValidatorReturns
	fake.recordInvocation("NewValidator", []interface{}{arg1})
	fake.newValidatorMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PPMFactory) NewValidatorCallCount() int {
	fake.newValidatorMutex.RLock()
	defer fake.newValidatorMutex.RUnlock()
	return len(fake.newValidatorArgsForCall)
}

func (fake *PPMFactory) NewValidatorCalls(stub func(driver.PublicParameters) (driver.Validator, error)) {
	fake.newValidatorMutex.Lock()
	defer fake.newValidatorMutex.Unlock()
	fake.NewValidatorStub = stub
}

func (fake *PPMFactory) NewValidatorArgsForCall(i int) driver.PublicParameters {
	fake.newValidatorMutex.RLock()
	defer fake.newValidatorMutex.RUnlock()
	argsForCall := fake.newValidatorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PPMFactory) NewValidatorReturns(result1 driver.Validator, result2 error) {
	fake.newValidatorMutex.Lock()
	defer fake.newValidatorMutex.Unlock()
	fake.NewValidatorStub = nil
	fake.newValidatorReturns = struct {
		result1 driver.Validator
		result2 error
	}{result1, result2}
}

func (fake *PPMFactory) NewValidatorReturnsOnCall(i int, result1 driver.Validator, result2 error) {
	fake.newValidatorMutex.Lock()
	defer fake.newValidatorMutex.Unlock()
	fake.NewValidatorStub = nil
	if fake.newValidatorReturnsOnCall == nil {
		fake.newValidatorReturnsOnCall = make(map[int]struct {
			result1 driver.Validator
			result2 error
		})
	}
	fake.newValidatorReturnsOnCall[i] = struct {
		result1 driver.Validator
		result2 error
	}{result1, result2}
}

func (fake *PPMFactory) PublicParametersFromBytes(arg1 []byte) (driver.PublicParameters, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.publicParametersFromBytesMutex.Lock()
	ret, specificReturn := fake.publicParametersFromBytesReturnsOnCall[len(fake.publicParametersFromBytesArgsForCall)]
	fake.publicParametersFromBytesArgsForCall = append(fake.publicParametersFromBytesArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.PublicParametersFromBytesStub
	fakeReturns := fake.publicParametersFromBytesReturns
	fake.recordInvocation("PublicParametersFromBytes", []interface{}{arg1Copy})
	fake.publicParametersFromBytesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PPMFactory) PublicParametersFromBytesCallCount() int {
	fake.publicParametersFromBytesMutex.RLock()
	defer fake.publicParametersFromBytesMutex.RUnlock()
	return len(fake.publicParametersFromBytesArgsForCall)
}

func (fake *PPMFactory) PublicParametersFromBytesCalls(stub func([]byte) (driver.PublicParameters, error)) {
	fake.publicParametersFromBytesMutex.Lock()
	defer fake.publicParametersFromBytesMutex.Unlock()
	fake.PublicParametersFromBytesStub = stub
}

func (fake *PPMFactory) PublicParametersFromBytesArgsForCall(i int) []byte {
	fake.publicParametersFromBytesMutex.RLock()
	defer fake.publicParametersFromBytesMutex.RUnlock()
	argsForCall := fake.publicParametersFromBytesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PPMFactory) PublicParametersFromBytesReturns(result1 driver.PublicParameters, result2 error) {
	fake.publicParametersFromBytesMutex.Lock()
	defer fake.publicParametersFromBytesMutex.Unlock()
	fake.PublicParametersFromBytesStub = nil
	fake.publicParametersFromBytesReturns = struct {
		result1 driver.PublicParameters
		result2 error
	}{result1, result2}
}

func (fake *PPMFactory) PublicParametersFromBytesReturnsOnCall(i int, result1 driver.PublicParameters, result2 error) {
	fake.publicParametersFromBytesMutex.Lock()
	defer fake.publicParametersFromBytesMutex.Unlock()
	fake.PublicParametersFromBytesStub = nil
	if fake.publicParametersFromBytesReturnsOnCall == nil {
		fake.publicParametersFromBytesReturnsOnCall = make(map[int]struct {
			result1 driver.PublicParameters
			result2 error
		})
	}
	fake.publicParametersFromBytesReturnsOnCall[i] = struct {
		result1 driver.PublicParameters
		result2 error
	}{result1, result2}
}

func (fake *PPMFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PPMFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.PPMFactory = new(PPMFactory)
