// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/ttx/dep/auditor"
)

type AuditServiceProvider struct {
	AuditorServiceStub        func(token.TMSID) (auditor.Service, auditor.StoreService, error)
	auditorServiceMutex       sync.RWMutex
	auditorServiceArgsForCall []struct {
		arg1 token.TMSID
	}
	auditorServiceReturns struct {
		result1 auditor.Service
		result2 auditor.StoreService
		result3 error
	}
	auditorServiceReturnsOnCall map[int]struct {
		result1 auditor.Service
		result2 auditor.StoreService
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AuditServiceProvider) AuditorService(arg1 token.TMSID) (auditor.Service, auditor.StoreService, error) {
	fake.auditorServiceMutex.Lock()
	ret, specificReturn := fake.auditorServiceReturnsOnCall[len(fake.auditorServiceArgsForCall)]
	fake.auditorServiceArgsForCall = append(fake.auditorServiceArgsForCall, struct {
		arg1 token.TMSID
	}{arg1})
	stub := fake.AuditorServiceStub
	fakeReturns := fake.auditorServiceReturns
	fake.recordInvocation("AuditorService", []interface{}{arg1})
	fake.auditorServiceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *AuditServiceProvider) AuditorServiceCallCount() int {
	fake.auditorServiceMutex.RLock()
	defer fake.auditorServiceMutex.RUnlock()
	return len(fake.auditorServiceArgsForCall)
}

func (fake *AuditServiceProvider) AuditorServiceCalls(stub func(token.TMSID) (auditor.Service, auditor.StoreService, error)) {
	fake.auditorServiceMutex.Lock()
	defer fake.auditorServiceMutex.Unlock()
	fake.AuditorServiceStub = stub
}

func (fake *AuditServiceProvider) AuditorServiceArgsForCall(i int) token.TMSID {
	fake.auditorServiceMutex.RLock()
	defer fake.auditorServiceMutex.RUnlock()
	argsForCall := fake.auditorServiceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *AuditServiceProvider) AuditorServiceReturns(result1 auditor.Service, result2 auditor.StoreService, result3 error) {
	fake.auditorServiceMutex.Lock()
	defer fake.auditorServiceMutex.Unlock()
	fake.AuditorServiceStub = nil
	fake.auditorServiceReturns = struct {
		result1 auditor.Service
		result2 auditor.StoreService
		result3 error
	}{result1, result2, result3}
}

func (fake *AuditServiceProvider) AuditorServiceReturnsOnCall(i int, result1 auditor.Service, result2 auditor.StoreService, result3 error) {
	fake.auditorServiceMutex.Lock()
	defer fake.auditorServiceMutex.Unlock()
	fake.AuditorServiceStub = nil
	if fake.auditorServiceReturnsOnCall == nil {
		fake.auditorServiceReturnsOnCall = make(map[int]struct {
			result1 auditor.Service
			result2 auditor.StoreService
			result3 error
		})
	}
	fake.auditorServiceReturnsOnCall[i] = struct {
		result1 auditor.Service
		result2 auditor.StoreService
		result3 error
	}{result1, result2, result3}
}

func (fake *AuditServiceProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.auditorServiceMutex.RLock()
	defer fake.auditorServiceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AuditServiceProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auditor.ServiceProvider = new(AuditServiceProvider)
