name: Feature
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for submitting a feature request! 😊

        Before submitting:
        * **Search existing issues** and discussions to see if something similar has been discussed previously.
        * **Consult the Resources**:
           - [Documentation Overview](https://github.com/hyperledger-labs/fabric-token-sdk/blob/main/docs/README.md)
           - [Development Guidelines](https://github.com/hyperledger-labs/fabric-token-sdk/blob/main/docs/development/development.md)
           - [Testing Guide](https://github.com/hyperledger-labs/fabric-token-sdk/blob/main/docs/development/testing.md)
        * **Consider opening a GitHub discussion** first to gather feedback and reach consensus.
        * If this is a major architectural change, please provide as much detail as possible.

        ---

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is the problem you are trying to solve?
      placeholder: I'm always frustrated when ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What solution do you propose to solve the problem?
      placeholder: |
        - Add a config property
        - Change the schema
        - ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What alternative solutions have you considered?
      placeholder: I considered using ... but ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
