// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/storage/db/driver"
)

type TokensService struct {
	AppendValidStub        func(context.Context, driver.Transaction, token.RequestAnchor, *token.Request) error
	appendValidMutex       sync.RWMutex
	appendValidArgsForCall []struct {
		arg1 context.Context
		arg2 driver.Transaction
		arg3 token.RequestAnchor
		arg4 *token.Request
	}
	appendValidReturns struct {
		result1 error
	}
	appendValidReturnsOnCall map[int]struct {
		result1 error
	}
	GetCachedTokenRequestStub        func(string) (*token.Request, []byte)
	getCachedTokenRequestMutex       sync.RWMutex
	getCachedTokenRequestArgsForCall []struct {
		arg1 string
	}
	getCachedTokenRequestReturns struct {
		result1 *token.Request
		result2 []byte
	}
	getCachedTokenRequestReturnsOnCall map[int]struct {
		result1 *token.Request
		result2 []byte
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TokensService) AppendValid(arg1 context.Context, arg2 driver.Transaction, arg3 token.RequestAnchor, arg4 *token.Request) error {
	fake.appendValidMutex.Lock()
	ret, specificReturn := fake.appendValidReturnsOnCall[len(fake.appendValidArgsForCall)]
	fake.appendValidArgsForCall = append(fake.appendValidArgsForCall, struct {
		arg1 context.Context
		arg2 driver.Transaction
		arg3 token.RequestAnchor
		arg4 *token.Request
	}{arg1, arg2, arg3, arg4})
	stub := fake.AppendValidStub
	fakeReturns := fake.appendValidReturns
	fake.recordInvocation("AppendValid", []interface{}{arg1, arg2, arg3, arg4})
	fake.appendValidMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TokensService) AppendValidCallCount() int {
	fake.appendValidMutex.RLock()
	defer fake.appendValidMutex.RUnlock()
	return len(fake.appendValidArgsForCall)
}

func (fake *TokensService) AppendValidCalls(stub func(context.Context, driver.Transaction, token.RequestAnchor, *token.Request) error) {
	fake.appendValidMutex.Lock()
	defer fake.appendValidMutex.Unlock()
	fake.AppendValidStub = stub
}

func (fake *TokensService) AppendValidArgsForCall(i int) (context.Context, driver.Transaction, token.RequestAnchor, *token.Request) {
	fake.appendValidMutex.RLock()
	defer fake.appendValidMutex.RUnlock()
	argsForCall := fake.appendValidArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *TokensService) AppendValidReturns(result1 error) {
	fake.appendValidMutex.Lock()
	defer fake.appendValidMutex.Unlock()
	fake.AppendValidStub = nil
	fake.appendValidReturns = struct {
		result1 error
	}{result1}
}

func (fake *TokensService) AppendValidReturnsOnCall(i int, result1 error) {
	fake.appendValidMutex.Lock()
	defer fake.appendValidMutex.Unlock()
	fake.AppendValidStub = nil
	if fake.appendValidReturnsOnCall == nil {
		fake.appendValidReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.appendValidReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *TokensService) GetCachedTokenRequest(arg1 string) (*token.Request, []byte) {
	fake.getCachedTokenRequestMutex.Lock()
	ret, specificReturn := fake.getCachedTokenRequestReturnsOnCall[len(fake.getCachedTokenRequestArgsForCall)]
	fake.getCachedTokenRequestArgsForCall = append(fake.getCachedTokenRequestArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetCachedTokenRequestStub
	fakeReturns := fake.getCachedTokenRequestReturns
	fake.recordInvocation("GetCachedTokenRequest", []interface{}{arg1})
	fake.getCachedTokenRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TokensService) GetCachedTokenRequestCallCount() int {
	fake.getCachedTokenRequestMutex.RLock()
	defer fake.getCachedTokenRequestMutex.RUnlock()
	return len(fake.getCachedTokenRequestArgsForCall)
}

func (fake *TokensService) GetCachedTokenRequestCalls(stub func(string) (*token.Request, []byte)) {
	fake.getCachedTokenRequestMutex.Lock()
	defer fake.getCachedTokenRequestMutex.Unlock()
	fake.GetCachedTokenRequestStub = stub
}

func (fake *TokensService) GetCachedTokenRequestArgsForCall(i int) string {
	fake.getCachedTokenRequestMutex.RLock()
	defer fake.getCachedTokenRequestMutex.RUnlock()
	argsForCall := fake.getCachedTokenRequestArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TokensService) GetCachedTokenRequestReturns(result1 *token.Request, result2 []byte) {
	fake.getCachedTokenRequestMutex.Lock()
	defer fake.getCachedTokenRequestMutex.Unlock()
	fake.GetCachedTokenRequestStub = nil
	fake.getCachedTokenRequestReturns = struct {
		result1 *token.Request
		result2 []byte
	}{result1, result2}
}

func (fake *TokensService) GetCachedTokenRequestReturnsOnCall(i int, result1 *token.Request, result2 []byte) {
	fake.getCachedTokenRequestMutex.Lock()
	defer fake.getCachedTokenRequestMutex.Unlock()
	fake.GetCachedTokenRequestStub = nil
	if fake.getCachedTokenRequestReturnsOnCall == nil {
		fake.getCachedTokenRequestReturnsOnCall = make(map[int]struct {
			result1 *token.Request
			result2 []byte
		})
	}
	fake.getCachedTokenRequestReturnsOnCall[i] = struct {
		result1 *token.Request
		result2 []byte
	}{result1, result2}
}

func (fake *TokensService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TokensService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
