// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/selector/sherdlock"
)

type FakeFetcherProvider struct {
	GetFetcherStub        func(token.TMSID) (sherdlock.TokenFetcher, error)
	getFetcherMutex       sync.RWMutex
	getFetcherArgsForCall []struct {
		arg1 token.TMSID
	}
	getFetcherReturns struct {
		result1 sherdlock.TokenFetcher
		result2 error
	}
	getFetcherReturnsOnCall map[int]struct {
		result1 sherdlock.TokenFetcher
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFetcherProvider) GetFetcher(arg1 token.TMSID) (sherdlock.TokenFetcher, error) {
	fake.getFetcherMutex.Lock()
	ret, specificReturn := fake.getFetcherReturnsOnCall[len(fake.getFetcherArgsForCall)]
	fake.getFetcherArgsForCall = append(fake.getFetcherArgsForCall, struct {
		arg1 token.TMSID
	}{arg1})
	stub := fake.GetFetcherStub
	fakeReturns := fake.getFetcherReturns
	fake.recordInvocation("GetFetcher", []interface{}{arg1})
	fake.getFetcherMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFetcherProvider) GetFetcherCallCount() int {
	fake.getFetcherMutex.RLock()
	defer fake.getFetcherMutex.RUnlock()
	return len(fake.getFetcherArgsForCall)
}

func (fake *FakeFetcherProvider) GetFetcherCalls(stub func(token.TMSID) (sherdlock.TokenFetcher, error)) {
	fake.getFetcherMutex.Lock()
	defer fake.getFetcherMutex.Unlock()
	fake.GetFetcherStub = stub
}

func (fake *FakeFetcherProvider) GetFetcherArgsForCall(i int) token.TMSID {
	fake.getFetcherMutex.RLock()
	defer fake.getFetcherMutex.RUnlock()
	argsForCall := fake.getFetcherArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFetcherProvider) GetFetcherReturns(result1 sherdlock.TokenFetcher, result2 error) {
	fake.getFetcherMutex.Lock()
	defer fake.getFetcherMutex.Unlock()
	fake.GetFetcherStub = nil
	fake.getFetcherReturns = struct {
		result1 sherdlock.TokenFetcher
		result2 error
	}{result1, result2}
}

func (fake *FakeFetcherProvider) GetFetcherReturnsOnCall(i int, result1 sherdlock.TokenFetcher, result2 error) {
	fake.getFetcherMutex.Lock()
	defer fake.getFetcherMutex.Unlock()
	fake.GetFetcherStub = nil
	if fake.getFetcherReturnsOnCall == nil {
		fake.getFetcherReturnsOnCall = make(map[int]struct {
			result1 sherdlock.TokenFetcher
			result2 error
		})
	}
	fake.getFetcherReturnsOnCall[i] = struct {
		result1 sherdlock.TokenFetcher
		result2 error
	}{result1, result2}
}

func (fake *FakeFetcherProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFetcherProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sherdlock.FetcherProvider = new(FakeFetcherProvider)
