/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package regression_test

import (
	"embed"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"path/filepath"
	"testing"

	math "github.com/IBM/mathlib"
	"github.com/hyperledger-labs/fabric-smart-client/pkg/utils/errors"
	"github.com/hyperledger-labs/fabric-token-sdk/token"
	"github.com/hyperledger-labs/fabric-token-sdk/token/core"
	"github.com/hyperledger-labs/fabric-token-sdk/token/core/common"
	fabtoken "github.com/hyperledger-labs/fabric-token-sdk/token/core/fabtoken/v1/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/core/zkatdlog/nogh/v1/audit"
	dlog "github.com/hyperledger-labs/fabric-token-sdk/token/core/zkatdlog/nogh/v1/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/core/zkatdlog/nogh/v1/setup"
	tokn "github.com/hyperledger-labs/fabric-token-sdk/token/core/zkatdlog/nogh/v1/token"
	"github.com/hyperledger-labs/fabric-token-sdk/token/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/logging"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/network/fabric/tcc"
	tk "github.com/hyperledger-labs/fabric-token-sdk/token/token"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/trace/noop"
)

//go:embed testdata
var testDataFS embed.FS

// ValidationFunc is a function that validates the results of UnmarshallAndVerifyWithMetadata.
// It receives the actions and metadata returned by the validator and returns an error if validation fails.
type ValidationFunc func(actions []any, metadata map[string][]byte) error

// TestRegression runs previously recorded regression test vectors contained in the
// `testdata/<variant>` directories. Each directory contains a `params.txt` file with
// base64-encoded public parameters and subdirectories for different action types
// (transfers, issues, redeems, swaps) with varying input/output combinations.
//
// Each subdirectory contains a single `testdata.json` file with 64 test cases in an
// aggregated format:
//
//	{
//	  "0": {"req_raw": "<base64>", "txid": "...", "metadata": "<base64>", "inputs": [...]},
//	  "1": {...},
//	  ...
//	  "63": {...}
//	}
//
// The test unmarshals each test case and verifies it against the validator to ensure
// the library remains backwards compatible.
//
// Notes:
//   - The testdata is generated by `testdata/zero/generator`. To regenerate vectors,
//     run that generator and commit the produced `testdata.json` files.
//   - The test expects exactly 64 test cases per configuration (keys "0" through "63").
//   - Each test case includes the token request, transaction ID, metadata, and input tokens.
func TestRegression(t *testing.T) {
	t.Parallel()
	for _, root := range []string{filepath.Join("testdata", "zero")} {
		for _, action := range []string{"transfers", "issues", "redeems", "swaps"} {
			// Select the appropriate validation function based on action type
			var validateFunc ValidationFunc
			switch action {
			case "transfers":
				validateFunc = validateTransfers
			case "issues":
				validateFunc = validateIssues
			case "redeems":
				validateFunc = validateRedeems
			case "swaps":
				validateFunc = validateSwaps
			default:
				t.Fatalf("unknown action type: %s", action)
			}

			testRegressionParallel(t, filepath.Join(root, "32-BLS12_381_BBS_GURVY"), action+"_i1_o1", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "32-BLS12_381_BBS_GURVY"), action+"_i1_o2", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "32-BLS12_381_BBS_GURVY"), action+"_i2_o1", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "32-BLS12_381_BBS_GURVY"), action+"_i2_o2", validateFunc)

			testRegressionParallel(t, filepath.Join(root, "64-BLS12_381_BBS_GURVY"), action+"_i1_o1", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "64-BLS12_381_BBS_GURVY"), action+"_i1_o2", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "64-BLS12_381_BBS_GURVY"), action+"_i2_o1", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "64-BLS12_381_BBS_GURVY"), action+"_i2_o2", validateFunc)

			testRegressionParallel(t, filepath.Join(root, "32-BN254"), action+"_i1_o1", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "32-BN254"), action+"_i1_o2", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "32-BN254"), action+"_i2_o1", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "32-BN254"), action+"_i2_o2", validateFunc)

			testRegressionParallel(t, filepath.Join(root, "64-BN254"), action+"_i1_o1", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "64-BN254"), action+"_i1_o2", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "64-BN254"), action+"_i2_o1", validateFunc)
			testRegressionParallel(t, filepath.Join(root, "64-BN254"), action+"_i2_o2", validateFunc)
		}
	}
}

func testRegressionParallel(t *testing.T, rootDir, subFolder string, validateFunc ValidationFunc) {
	t.Helper()
	t.Run(fmt.Sprintf("%s-%s", rootDir, subFolder), func(t *testing.T) {
		t.Parallel()
		testRegression(t, rootDir, subFolder, validateFunc)
	})
}

func testRegression(t *testing.T, rootDir, subFolder string, validateFunc ValidationFunc) {
	t.Helper()
	t.Logf("regression test for [%s:%s]", rootDir, subFolder)
	paramsData, err := testDataFS.ReadFile(filepath.Join(rootDir, "params.txt"))
	require.NoError(t, err)

	ppRaw, err := base64.StdEncoding.DecodeString(string(paramsData))
	require.NoError(t, err)

	pp, tokenValidator, err := tokenServicesFactory(ppRaw)
	require.NoError(t, err)

	// Create auditor for metadata validation
	auditor := createAuditor(pp)

	// Read aggregated test data file
	filePath := filepath.Join(rootDir, subFolder, "testdata.json")
	jsonData, err := testDataFS.ReadFile(filePath)
	require.NoError(t, err, "failed to read aggregated test data from [%s]", filePath)

	// Parse aggregated test cases
	var allTestCases map[string]struct {
		ReqRaw   string     `json:"req_raw"`
		TXID     string     `json:"txid"`
		Metadata string     `json:"metadata,omitempty"`
		Inputs   [][][]byte `json:"inputs,omitempty"`
	}
	err = json.Unmarshal(jsonData, &allTestCases)
	require.NoError(t, err, "failed to unmarshal aggregated test data from [%s]", filePath)

	// Process each test case
	for testCaseKey, tokenData := range allTestCases {
		// Decode base64-encoded request
		reqRaw, err := base64.StdEncoding.DecodeString(tokenData.ReqRaw)
		require.NoError(t, err, "failed to decode req_raw for test case %s", testCaseKey)

		actions, metadata, err := tokenValidator.UnmarshallAndVerifyWithMetadata(
			t.Context(),
			&fakeLedger{},
			token.RequestAnchor(tokenData.TXID),
			reqRaw,
		)
		require.NoError(t, err, "failed verification of the token request for test case %s", testCaseKey)

		// Validate the results
		err = validateFunc(actions, metadata)
		require.NoError(t, err, "validation failed for token request for test case %s", testCaseKey)

		// Decode and validate metadata if available
		if tokenData.Metadata != "" {
			metadataRaw, err := base64.StdEncoding.DecodeString(tokenData.Metadata)
			require.NoError(t, err, "failed to decode metadata for test case %s", testCaseKey)

			// Perform auditor validation
			requestMetadata := new(driver.TokenRequestMetadata)
			err = requestMetadata.FromBytes(metadataRaw)
			require.NoError(t, err, "failed to unmarshal metadata for test case %s", testCaseKey)

			// Deserialize inputs if available
			var inputTokens [][]*tokn.Token
			if tokenData.Inputs != nil {
				inputTokens, err = deserializeInputs(tokenData.Inputs, pp)
				require.NoError(t, err, "failed to deserialize inputs for test case %s", testCaseKey)
			}

			// Deserialize token request for auditor check
			tokenRequest := &driver.TokenRequest{}
			err = tokenRequest.FromBytes(reqRaw)
			require.NoError(t, err, "failed to deserialize token request for test case %s", testCaseKey)

			// Perform auditor check with inputs
			err = auditor.Check(t.Context(), tokenRequest, requestMetadata, inputTokens, driver.TokenRequestAnchor(tokenData.TXID))
			require.NoError(t, err, "auditor check failed for token request for test case %s", testCaseKey)
		}
	}
}

func tokenServicesFactory(bytes []byte) (tcc.PublicParameters, tcc.Validator, error) {
	is := core.NewValidatorDriverService(fabtoken.NewValidatorDriver(), dlog.NewValidatorDriver())

	ppm, err := is.PublicParametersFromBytes(bytes)
	if err != nil {
		return nil, nil, err
	}
	if err := ppm.Validate(); err != nil {
		return nil, nil, err
	}
	v, err := is.NewValidator(ppm)
	if err != nil {
		return nil, nil, err
	}

	return ppm, token.NewValidator(v), nil
}

// createAuditor creates an auditor instance for the given public parameters
func createAuditor(pp tcc.PublicParameters) *audit.Auditor {
	// Cast to concrete type to access curve and other fields
	v1pp, ok := pp.(*setup.PublicParams)
	if !ok {
		panic("expected setup.PublicParams")
	}

	c := math.Curves[v1pp.Curve]
	deserializer, err := dlog.NewDeserializer(v1pp)
	if err != nil {
		panic(err)
	}

	return audit.NewAuditor(
		logging.MustGetLogger(),
		&noop.Tracer{},
		deserializer,
		v1pp.PedersenGenerators,
		c,
	)
}

// deserializeInputs deserializes input tokens from the serialized format
func deserializeInputs(serializedInputs [][][]byte, pp tcc.PublicParameters) ([][]*tokn.Token, error) {
	var res [][]*tokn.Token

	// Deserialize each token
	for i, action := range serializedInputs {
		// inputs for action i
		if action == nil {
			return nil, errors.Errorf("serialized input %d is nil", i)
		}
		tokens := make([]*tokn.Token, 0, len(action))
		for j, input := range action {
			if input == nil {
				continue
			}
			tok := &tokn.Token{}
			if err := tok.Deserialize(input); err != nil {
				return nil, errors.Errorf("failed to deserialize token [%d:%d]: %w", i, j, err)
			}
			tokens = append(tokens, tok)
		}
		res = append(res, tokens)
	}

	return res, nil
}

func validateMetadata(metadata map[string][]byte) error {
	if len(metadata) < 2 {
		return errors.Errorf("expected at least 2 metadata entries, got %d", len(metadata))
	}

	requiredKeys := []driver.ValidationAttributeID{
		common.TokenRequestToSign,
		common.TokenRequestSignatures,
	}
	for _, key := range requiredKeys {
		value, ok := metadata[key]
		if !ok {
			return errors.Errorf("missing metadata entry %q", key)
		}
		if len(value) == 0 {
			return errors.Errorf("metadata entry %q is empty", key)
		}
	}

	return nil
}

func validateOutputs(outputs []driver.Output, expectedNumOutputs int, expectedRedeemOutputs int) error {
	if len(outputs) != expectedNumOutputs {
		return errors.Errorf("expected %d outputs, got %d", expectedNumOutputs, len(outputs))
	}

	redeemOutputs := 0
	for i, output := range outputs {
		if output == nil {
			return errors.Errorf("output %d is nil", i)
		}
		if output.IsRedeem() {
			redeemOutputs++
			if len(output.GetOwner()) != 0 {
				return errors.Errorf("redeem output %d has unexpected owner", i)
			}

			continue
		}
		if len(output.GetOwner()) == 0 {
			return errors.Errorf("non-redeem output %d has empty owner", i)
		}
	}

	if redeemOutputs != expectedRedeemOutputs {
		return errors.Errorf("expected %d redeem outputs, got %d", expectedRedeemOutputs, redeemOutputs)
	}

	return nil
}

// validateIssues validates that the actions match the issue requests generated in env.go.
func validateIssues(actions []any, metadata map[string][]byte) error {
	if len(actions) != 1 {
		return errors.Errorf("expected 1 action for issues, got %d", len(actions))
	}

	issueAction, ok := actions[0].(driver.IssueAction)
	if !ok {
		return errors.Errorf("action does not implement driver.IssueAction interface, got type %T", actions[0])
	}
	if issueAction.NumInputs() != 0 {
		return errors.Errorf("expected issue action to have 0 inputs, got %d", issueAction.NumInputs())
	}
	if issueAction.IsAnonymous() {
		return errors.Errorf("expected issue action to be non-anonymous")
	}
	if issueAction.IsGraphHiding() {
		return errors.Errorf("expected issue action to be non-graph-hiding")
	}
	if len(issueAction.GetIssuer()) == 0 {
		return errors.Errorf("expected issue action issuer to be set")
	}
	if len(issueAction.ExtraSigners()) != 0 {
		return errors.Errorf("expected issue action to have no extra signers, got %d", len(issueAction.ExtraSigners()))
	}
	if err := validateOutputs(issueAction.GetOutputs(), 1, 0); err != nil {
		return errors.Errorf("invalid issue outputs: %w", err)
	}
	if err := validateMetadata(metadata); err != nil {
		return errors.Errorf("invalid issue metadata: %w", err)
	}

	return nil
}

// validateTransfers validates that the actions match the transfer requests generated in env.go.
func validateTransfers(actions []any, metadata map[string][]byte) error {
	if len(actions) != 1 {
		return errors.Errorf("expected exactly 1 action for transfers, got %d", len(actions))
	}

	transferAction, ok := actions[0].(driver.TransferAction)
	if !ok {
		return errors.Errorf("action does not implement driver.TransferAction interface, got type %T", actions[0])
	}
	if transferAction.NumInputs() == 0 {
		return errors.Errorf("expected transfer action to have at least 1 input")
	}
	if transferAction.NumOutputs() == 0 {
		return errors.Errorf("expected transfer action to have at least 1 output")
	}
	if transferAction.IsGraphHiding() {
		return errors.Errorf("expected transfer action to be non-graph-hiding")
	}
	if transferAction.GetIssuer() != nil {
		return errors.Errorf("expected transfer action issuer to be nil")
	}
	for i := range transferAction.NumOutputs() {
		if transferAction.IsRedeemAt(i) {
			return errors.Errorf("transfer output %d unexpectedly marked as redeem", i)
		}
	}
	if err := validateOutputs(transferAction.GetOutputs(), transferAction.NumOutputs(), 0); err != nil {
		return errors.Errorf("invalid transfer outputs: %w", err)
	}
	if err := validateMetadata(metadata); err != nil {
		return errors.Errorf("invalid transfer metadata: %w", err)
	}

	return nil
}

// validateRedeems validates that the actions match the redeem requests generated in env.go.
func validateRedeems(actions []any, metadata map[string][]byte) error {
	if len(actions) != 1 {
		return errors.Errorf("expected exactly 1 action for redeems, got %d", len(actions))
	}

	transferAction, ok := actions[0].(driver.TransferAction)
	if !ok {
		return errors.Errorf("action does not implement driver.TransferAction interface, got type %T", actions[0])
	}
	if transferAction.NumInputs() == 0 {
		return errors.Errorf("expected redeem action to have at least 1 input")
	}
	if transferAction.NumOutputs() != 2 {
		return errors.Errorf("expected redeem action to have 2 outputs, got %d", transferAction.NumOutputs())
	}
	if transferAction.IsGraphHiding() {
		return errors.Errorf("expected redeem action to be non-graph-hiding")
	}
	if transferAction.GetIssuer() == nil {
		return errors.Errorf("expected redeem action issuer to be set")
	}

	redeemOutputs := 0
	for i := range transferAction.NumOutputs() {
		if transferAction.IsRedeemAt(i) {
			redeemOutputs++
		}
	}
	if redeemOutputs == 0 {
		return errors.Errorf("expected redeem action to have at least 1 redeem output")
	}
	if err := validateOutputs(transferAction.GetOutputs(), 2, redeemOutputs); err != nil {
		return errors.Errorf("invalid redeem outputs: %w", err)
	}
	if err := validateMetadata(metadata); err != nil {
		return errors.Errorf("invalid redeem metadata: %w", err)
	}

	return nil
}

// validateSwaps validates that the actions match the swap requests generated in env.go.
func validateSwaps(actions []any, metadata map[string][]byte) error {
	if len(actions) != 2 {
		return errors.Errorf("expected exactly 2 actions for swaps, got %d", len(actions))
	}

	for i, action := range actions {
		transferAction, ok := action.(driver.TransferAction)
		if !ok {
			return errors.Errorf("action %d does not implement driver.TransferAction interface, got type %T", i, action)
		}
		if transferAction.NumInputs() == 0 {
			return errors.Errorf("swap action %d has 0 inputs, expected at least 1", i)
		}
		if transferAction.NumOutputs() == 0 {
			return errors.Errorf("swap action %d has 0 outputs, expected at least 1", i)
		}
		if transferAction.IsGraphHiding() {
			return errors.Errorf("expected swap action %d to be non-graph-hiding", i)
		}
		if transferAction.GetIssuer() != nil {
			return errors.Errorf("expected swap action %d issuer to be nil", i)
		}
		for j := range transferAction.NumOutputs() {
			if transferAction.IsRedeemAt(j) {
				return errors.Errorf("swap action %d output %d unexpectedly marked as redeem", i, j)
			}
		}
		if err := validateOutputs(transferAction.GetOutputs(), transferAction.NumOutputs(), 0); err != nil {
			return errors.Errorf("invalid swap outputs for action %d: %w", i, err)
		}
	}

	if err := validateMetadata(metadata); err != nil {
		return errors.Errorf("invalid swap metadata: %w", err)
	}

	return nil
}

type fakeLedger struct{}

func (*fakeLedger) GetState(_ tk.ID) ([]byte, error) {
	panic("ciao")
}
