//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ftactions.proto

package actions

import (
	v1 "github.com/hyperledger-labs/fabric-token-sdk/token/driver/protos-go/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         []byte                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`       // is the token owner
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`         // is the type of the token
	Quantity      string                 `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"` // is the number of units of Type carried in the token. It is encoded as a string containing a number in base 16. The string has prefix ``0x''.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_ftactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Token) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Token) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type TransferActionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       *v1.TokenID            `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Input         *Token                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferActionInput) Reset() {
	*x = TransferActionInput{}
	mi := &file_ftactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferActionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferActionInput) ProtoMessage() {}

func (x *TransferActionInput) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferActionInput.ProtoReflect.Descriptor instead.
func (*TransferActionInput) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{1}
}

func (x *TransferActionInput) GetTokenId() *v1.TokenID {
	if x != nil {
		return x.TokenId
	}
	return nil
}

func (x *TransferActionInput) GetInput() *Token {
	if x != nil {
		return x.Input
	}
	return nil
}

type TransferActionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // Token is the new token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferActionOutput) Reset() {
	*x = TransferActionOutput{}
	mi := &file_ftactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferActionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferActionOutput) ProtoMessage() {}

func (x *TransferActionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferActionOutput.ProtoReflect.Descriptor instead.
func (*TransferActionOutput) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{2}
}

func (x *TransferActionOutput) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type TransferAction struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Version       uint64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Inputs        []*TransferActionInput  `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`                                                                               // inputs
	Outputs       []*TransferActionOutput `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`                                                                             // outputs
	Metadata      map[string][]byte       `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadata contains the transfer action's metadata
	Issuer        *v1.Identity            `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`                                                                               // is the identity of issuer to sign the transfer action
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferAction) Reset() {
	*x = TransferAction{}
	mi := &file_ftactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAction) ProtoMessage() {}

func (x *TransferAction) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAction.ProtoReflect.Descriptor instead.
func (*TransferAction) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{3}
}

func (x *TransferAction) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TransferAction) GetInputs() []*TransferActionInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *TransferAction) GetOutputs() []*TransferActionOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TransferAction) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TransferAction) GetIssuer() *v1.Identity {
	if x != nil {
		return x.Issuer
	}
	return nil
}

type IssueActionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.TokenID            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // is the token id of the token to be redeemed
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // is the actual token to be redeemed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueActionInput) Reset() {
	*x = IssueActionInput{}
	mi := &file_ftactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueActionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueActionInput) ProtoMessage() {}

func (x *IssueActionInput) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueActionInput.ProtoReflect.Descriptor instead.
func (*IssueActionInput) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{4}
}

func (x *IssueActionInput) GetId() *v1.TokenID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *IssueActionInput) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type IssueActionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // is the newly issued token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueActionOutput) Reset() {
	*x = IssueActionOutput{}
	mi := &file_ftactions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueActionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueActionOutput) ProtoMessage() {}

func (x *IssueActionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueActionOutput.ProtoReflect.Descriptor instead.
func (*IssueActionOutput) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{5}
}

func (x *IssueActionOutput) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type IssueAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Issuer        *v1.Identity           `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`                                                                               // is the identity of issuer
	Inputs        []*IssueActionInput    `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`                                                                               // are the tokens to be redeemed by this issue action
	Outputs       []*IssueActionOutput   `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`                                                                             // are the newly issued tokens
	Metadata      map[string][]byte      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadata of the issue action
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueAction) Reset() {
	*x = IssueAction{}
	mi := &file_ftactions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAction) ProtoMessage() {}

func (x *IssueAction) ProtoReflect() protoreflect.Message {
	mi := &file_ftactions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAction.ProtoReflect.Descriptor instead.
func (*IssueAction) Descriptor() ([]byte, []int) {
	return file_ftactions_proto_rawDescGZIP(), []int{6}
}

func (x *IssueAction) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *IssueAction) GetIssuer() *v1.Identity {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *IssueAction) GetInputs() []*IssueActionInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *IssueAction) GetOutputs() []*IssueActionOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *IssueAction) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_ftactions_proto protoreflect.FileDescriptor

const file_ftactions_proto_rawDesc = "" +
	"\n" +
	"\x0fftactions.proto\x12\"fabric_token_sdk.token.fabtoken.v1\x1a\fcommon.proto\"M\n" +
	"\x05Token\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\fR\x05owner\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\tR\bquantity\"\x9c\x01\n" +
	"\x13TransferActionInput\x12D\n" +
	"\btoken_id\x18\x01 \x01(\v2).fabric_token_sdk.token.driver.v1.TokenIDR\atokenId\x12?\n" +
	"\x05input\x18\x02 \x01(\v2).fabric_token_sdk.token.fabtoken.v1.TokenR\x05input\"W\n" +
	"\x14TransferActionOutput\x12?\n" +
	"\x05token\x18\x01 \x01(\v2).fabric_token_sdk.token.fabtoken.v1.TokenR\x05token\"\xae\x03\n" +
	"\x0eTransferAction\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12O\n" +
	"\x06inputs\x18\x02 \x03(\v27.fabric_token_sdk.token.fabtoken.v1.TransferActionInputR\x06inputs\x12R\n" +
	"\aoutputs\x18\x03 \x03(\v28.fabric_token_sdk.token.fabtoken.v1.TransferActionOutputR\aoutputs\x12\\\n" +
	"\bmetadata\x18\x04 \x03(\v2@.fabric_token_sdk.token.fabtoken.v1.TransferAction.MetadataEntryR\bmetadata\x12B\n" +
	"\x06issuer\x18\x05 \x01(\v2*.fabric_token_sdk.token.driver.v1.IdentityR\x06issuer\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"c\n" +
	"\x10IssueActionInput\x129\n" +
	"\x02id\x18\x01 \x01(\v2).fabric_token_sdk.token.driver.v1.TokenIDR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\"T\n" +
	"\x11IssueActionOutput\x12?\n" +
	"\x05token\x18\x01 \x01(\v2).fabric_token_sdk.token.fabtoken.v1.TokenR\x05token\"\xa2\x03\n" +
	"\vIssueAction\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12B\n" +
	"\x06issuer\x18\x02 \x01(\v2*.fabric_token_sdk.token.driver.v1.IdentityR\x06issuer\x12L\n" +
	"\x06inputs\x18\x03 \x03(\v24.fabric_token_sdk.token.fabtoken.v1.IssueActionInputR\x06inputs\x12O\n" +
	"\aoutputs\x18\x04 \x03(\v25.fabric_token_sdk.token.fabtoken.v1.IssueActionOutputR\aoutputs\x12Y\n" +
	"\bmetadata\x18\x05 \x03(\v2=.fabric_token_sdk.token.fabtoken.v1.IssueAction.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01BWZUgithub.com/hyperledger-labs/fabric-token-sdk/token/core/fabtoken/protos-go/v1/actionsb\x06proto3"

var (
	file_ftactions_proto_rawDescOnce sync.Once
	file_ftactions_proto_rawDescData []byte
)

func file_ftactions_proto_rawDescGZIP() []byte {
	file_ftactions_proto_rawDescOnce.Do(func() {
		file_ftactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ftactions_proto_rawDesc), len(file_ftactions_proto_rawDesc)))
	})
	return file_ftactions_proto_rawDescData
}

var file_ftactions_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ftactions_proto_goTypes = []any{
	(*Token)(nil),                // 0: fabric_token_sdk.token.fabtoken.v1.Token
	(*TransferActionInput)(nil),  // 1: fabric_token_sdk.token.fabtoken.v1.TransferActionInput
	(*TransferActionOutput)(nil), // 2: fabric_token_sdk.token.fabtoken.v1.TransferActionOutput
	(*TransferAction)(nil),       // 3: fabric_token_sdk.token.fabtoken.v1.TransferAction
	(*IssueActionInput)(nil),     // 4: fabric_token_sdk.token.fabtoken.v1.IssueActionInput
	(*IssueActionOutput)(nil),    // 5: fabric_token_sdk.token.fabtoken.v1.IssueActionOutput
	(*IssueAction)(nil),          // 6: fabric_token_sdk.token.fabtoken.v1.IssueAction
	nil,                          // 7: fabric_token_sdk.token.fabtoken.v1.TransferAction.MetadataEntry
	nil,                          // 8: fabric_token_sdk.token.fabtoken.v1.IssueAction.MetadataEntry
	(*v1.TokenID)(nil),           // 9: fabric_token_sdk.token.driver.v1.TokenID
	(*v1.Identity)(nil),          // 10: fabric_token_sdk.token.driver.v1.Identity
}
var file_ftactions_proto_depIdxs = []int32{
	9,  // 0: fabric_token_sdk.token.fabtoken.v1.TransferActionInput.token_id:type_name -> fabric_token_sdk.token.driver.v1.TokenID
	0,  // 1: fabric_token_sdk.token.fabtoken.v1.TransferActionInput.input:type_name -> fabric_token_sdk.token.fabtoken.v1.Token
	0,  // 2: fabric_token_sdk.token.fabtoken.v1.TransferActionOutput.token:type_name -> fabric_token_sdk.token.fabtoken.v1.Token
	1,  // 3: fabric_token_sdk.token.fabtoken.v1.TransferAction.inputs:type_name -> fabric_token_sdk.token.fabtoken.v1.TransferActionInput
	2,  // 4: fabric_token_sdk.token.fabtoken.v1.TransferAction.outputs:type_name -> fabric_token_sdk.token.fabtoken.v1.TransferActionOutput
	7,  // 5: fabric_token_sdk.token.fabtoken.v1.TransferAction.metadata:type_name -> fabric_token_sdk.token.fabtoken.v1.TransferAction.MetadataEntry
	10, // 6: fabric_token_sdk.token.fabtoken.v1.TransferAction.issuer:type_name -> fabric_token_sdk.token.driver.v1.Identity
	9,  // 7: fabric_token_sdk.token.fabtoken.v1.IssueActionInput.id:type_name -> fabric_token_sdk.token.driver.v1.TokenID
	0,  // 8: fabric_token_sdk.token.fabtoken.v1.IssueActionOutput.token:type_name -> fabric_token_sdk.token.fabtoken.v1.Token
	10, // 9: fabric_token_sdk.token.fabtoken.v1.IssueAction.issuer:type_name -> fabric_token_sdk.token.driver.v1.Identity
	4,  // 10: fabric_token_sdk.token.fabtoken.v1.IssueAction.inputs:type_name -> fabric_token_sdk.token.fabtoken.v1.IssueActionInput
	5,  // 11: fabric_token_sdk.token.fabtoken.v1.IssueAction.outputs:type_name -> fabric_token_sdk.token.fabtoken.v1.IssueActionOutput
	8,  // 12: fabric_token_sdk.token.fabtoken.v1.IssueAction.metadata:type_name -> fabric_token_sdk.token.fabtoken.v1.IssueAction.MetadataEntry
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_ftactions_proto_init() }
func file_ftactions_proto_init() {
	if File_ftactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ftactions_proto_rawDesc), len(file_ftactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ftactions_proto_goTypes,
		DependencyIndexes: file_ftactions_proto_depIdxs,
		MessageInfos:      file_ftactions_proto_msgTypes,
	}.Build()
	File_ftactions_proto = out.File
	file_ftactions_proto_goTypes = nil
	file_ftactions_proto_depIdxs = nil
}
