// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/ttx"
)

type StorageProvider struct {
	CacheRequestStub        func(context.Context, token.TMSID, *token.Request) error
	cacheRequestMutex       sync.RWMutex
	cacheRequestArgsForCall []struct {
		arg1 context.Context
		arg2 token.TMSID
		arg3 *token.Request
	}
	cacheRequestReturns struct {
		result1 error
	}
	cacheRequestReturnsOnCall map[int]struct {
		result1 error
	}
	GetStorageStub        func(token.TMSID) (ttx.Storage, error)
	getStorageMutex       sync.RWMutex
	getStorageArgsForCall []struct {
		arg1 token.TMSID
	}
	getStorageReturns struct {
		result1 ttx.Storage
		result2 error
	}
	getStorageReturnsOnCall map[int]struct {
		result1 ttx.Storage
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *StorageProvider) CacheRequest(arg1 context.Context, arg2 token.TMSID, arg3 *token.Request) error {
	fake.cacheRequestMutex.Lock()
	ret, specificReturn := fake.cacheRequestReturnsOnCall[len(fake.cacheRequestArgsForCall)]
	fake.cacheRequestArgsForCall = append(fake.cacheRequestArgsForCall, struct {
		arg1 context.Context
		arg2 token.TMSID
		arg3 *token.Request
	}{arg1, arg2, arg3})
	stub := fake.CacheRequestStub
	fakeReturns := fake.cacheRequestReturns
	fake.recordInvocation("CacheRequest", []interface{}{arg1, arg2, arg3})
	fake.cacheRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *StorageProvider) CacheRequestCallCount() int {
	fake.cacheRequestMutex.RLock()
	defer fake.cacheRequestMutex.RUnlock()
	return len(fake.cacheRequestArgsForCall)
}

func (fake *StorageProvider) CacheRequestCalls(stub func(context.Context, token.TMSID, *token.Request) error) {
	fake.cacheRequestMutex.Lock()
	defer fake.cacheRequestMutex.Unlock()
	fake.CacheRequestStub = stub
}

func (fake *StorageProvider) CacheRequestArgsForCall(i int) (context.Context, token.TMSID, *token.Request) {
	fake.cacheRequestMutex.RLock()
	defer fake.cacheRequestMutex.RUnlock()
	argsForCall := fake.cacheRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *StorageProvider) CacheRequestReturns(result1 error) {
	fake.cacheRequestMutex.Lock()
	defer fake.cacheRequestMutex.Unlock()
	fake.CacheRequestStub = nil
	fake.cacheRequestReturns = struct {
		result1 error
	}{result1}
}

func (fake *StorageProvider) CacheRequestReturnsOnCall(i int, result1 error) {
	fake.cacheRequestMutex.Lock()
	defer fake.cacheRequestMutex.Unlock()
	fake.CacheRequestStub = nil
	if fake.cacheRequestReturnsOnCall == nil {
		fake.cacheRequestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.cacheRequestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *StorageProvider) GetStorage(arg1 token.TMSID) (ttx.Storage, error) {
	fake.getStorageMutex.Lock()
	ret, specificReturn := fake.getStorageReturnsOnCall[len(fake.getStorageArgsForCall)]
	fake.getStorageArgsForCall = append(fake.getStorageArgsForCall, struct {
		arg1 token.TMSID
	}{arg1})
	stub := fake.GetStorageStub
	fakeReturns := fake.getStorageReturns
	fake.recordInvocation("GetStorage", []interface{}{arg1})
	fake.getStorageMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *StorageProvider) GetStorageCallCount() int {
	fake.getStorageMutex.RLock()
	defer fake.getStorageMutex.RUnlock()
	return len(fake.getStorageArgsForCall)
}

func (fake *StorageProvider) GetStorageCalls(stub func(token.TMSID) (ttx.Storage, error)) {
	fake.getStorageMutex.Lock()
	defer fake.getStorageMutex.Unlock()
	fake.GetStorageStub = stub
}

func (fake *StorageProvider) GetStorageArgsForCall(i int) token.TMSID {
	fake.getStorageMutex.RLock()
	defer fake.getStorageMutex.RUnlock()
	argsForCall := fake.getStorageArgsForCall[i]
	return argsForCall.arg1
}

func (fake *StorageProvider) GetStorageReturns(result1 ttx.Storage, result2 error) {
	fake.getStorageMutex.Lock()
	defer fake.getStorageMutex.Unlock()
	fake.GetStorageStub = nil
	fake.getStorageReturns = struct {
		result1 ttx.Storage
		result2 error
	}{result1, result2}
}

func (fake *StorageProvider) GetStorageReturnsOnCall(i int, result1 ttx.Storage, result2 error) {
	fake.getStorageMutex.Lock()
	defer fake.getStorageMutex.Unlock()
	fake.GetStorageStub = nil
	if fake.getStorageReturnsOnCall == nil {
		fake.getStorageReturnsOnCall = make(map[int]struct {
			result1 ttx.Storage
			result2 error
		})
	}
	fake.getStorageReturnsOnCall[i] = struct {
		result1 ttx.Storage
		result2 error
	}{result1, result2}
}

func (fake *StorageProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *StorageProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ttx.StorageProvider = new(StorageProvider)
