// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/services/identity/driver"
)

type AuditInfoDeserializer struct {
	DeserializeAuditInfoStub        func(context.Context, []byte) (driver.AuditInfo, error)
	deserializeAuditInfoMutex       sync.RWMutex
	deserializeAuditInfoArgsForCall []struct {
		arg1 context.Context
		arg2 []byte
	}
	deserializeAuditInfoReturns struct {
		result1 driver.AuditInfo
		result2 error
	}
	deserializeAuditInfoReturnsOnCall map[int]struct {
		result1 driver.AuditInfo
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *AuditInfoDeserializer) DeserializeAuditInfo(arg1 context.Context, arg2 []byte) (driver.AuditInfo, error) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.deserializeAuditInfoMutex.Lock()
	ret, specificReturn := fake.deserializeAuditInfoReturnsOnCall[len(fake.deserializeAuditInfoArgsForCall)]
	fake.deserializeAuditInfoArgsForCall = append(fake.deserializeAuditInfoArgsForCall, struct {
		arg1 context.Context
		arg2 []byte
	}{arg1, arg2Copy})
	stub := fake.DeserializeAuditInfoStub
	fakeReturns := fake.deserializeAuditInfoReturns
	fake.recordInvocation("DeserializeAuditInfo", []interface{}{arg1, arg2Copy})
	fake.deserializeAuditInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *AuditInfoDeserializer) DeserializeAuditInfoCallCount() int {
	fake.deserializeAuditInfoMutex.RLock()
	defer fake.deserializeAuditInfoMutex.RUnlock()
	return len(fake.deserializeAuditInfoArgsForCall)
}

func (fake *AuditInfoDeserializer) DeserializeAuditInfoCalls(stub func(context.Context, []byte) (driver.AuditInfo, error)) {
	fake.deserializeAuditInfoMutex.Lock()
	defer fake.deserializeAuditInfoMutex.Unlock()
	fake.DeserializeAuditInfoStub = stub
}

func (fake *AuditInfoDeserializer) DeserializeAuditInfoArgsForCall(i int) (context.Context, []byte) {
	fake.deserializeAuditInfoMutex.RLock()
	defer fake.deserializeAuditInfoMutex.RUnlock()
	argsForCall := fake.deserializeAuditInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *AuditInfoDeserializer) DeserializeAuditInfoReturns(result1 driver.AuditInfo, result2 error) {
	fake.deserializeAuditInfoMutex.Lock()
	defer fake.deserializeAuditInfoMutex.Unlock()
	fake.DeserializeAuditInfoStub = nil
	fake.deserializeAuditInfoReturns = struct {
		result1 driver.AuditInfo
		result2 error
	}{result1, result2}
}

func (fake *AuditInfoDeserializer) DeserializeAuditInfoReturnsOnCall(i int, result1 driver.AuditInfo, result2 error) {
	fake.deserializeAuditInfoMutex.Lock()
	defer fake.deserializeAuditInfoMutex.Unlock()
	fake.DeserializeAuditInfoStub = nil
	if fake.deserializeAuditInfoReturnsOnCall == nil {
		fake.deserializeAuditInfoReturnsOnCall = make(map[int]struct {
			result1 driver.AuditInfo
			result2 error
		})
	}
	fake.deserializeAuditInfoReturnsOnCall[i] = struct {
		result1 driver.AuditInfo
		result2 error
	}{result1, result2}
}

func (fake *AuditInfoDeserializer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *AuditInfoDeserializer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.AuditInfoDeserializer = new(AuditInfoDeserializer)
