// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token/services/identity/driver"
)

type Config struct {
	CacheSizeForOwnerIDStub        func(string) int
	cacheSizeForOwnerIDMutex       sync.RWMutex
	cacheSizeForOwnerIDArgsForCall []struct {
		arg1 string
	}
	cacheSizeForOwnerIDReturns struct {
		result1 int
	}
	cacheSizeForOwnerIDReturnsOnCall map[int]struct {
		result1 int
	}
	TranslatePathStub        func(string) string
	translatePathMutex       sync.RWMutex
	translatePathArgsForCall []struct {
		arg1 string
	}
	translatePathReturns struct {
		result1 string
	}
	translatePathReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Config) CacheSizeForOwnerID(arg1 string) int {
	fake.cacheSizeForOwnerIDMutex.Lock()
	ret, specificReturn := fake.cacheSizeForOwnerIDReturnsOnCall[len(fake.cacheSizeForOwnerIDArgsForCall)]
	fake.cacheSizeForOwnerIDArgsForCall = append(fake.cacheSizeForOwnerIDArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CacheSizeForOwnerIDStub
	fakeReturns := fake.cacheSizeForOwnerIDReturns
	fake.recordInvocation("CacheSizeForOwnerID", []interface{}{arg1})
	fake.cacheSizeForOwnerIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Config) CacheSizeForOwnerIDCallCount() int {
	fake.cacheSizeForOwnerIDMutex.RLock()
	defer fake.cacheSizeForOwnerIDMutex.RUnlock()
	return len(fake.cacheSizeForOwnerIDArgsForCall)
}

func (fake *Config) CacheSizeForOwnerIDCalls(stub func(string) int) {
	fake.cacheSizeForOwnerIDMutex.Lock()
	defer fake.cacheSizeForOwnerIDMutex.Unlock()
	fake.CacheSizeForOwnerIDStub = stub
}

func (fake *Config) CacheSizeForOwnerIDArgsForCall(i int) string {
	fake.cacheSizeForOwnerIDMutex.RLock()
	defer fake.cacheSizeForOwnerIDMutex.RUnlock()
	argsForCall := fake.cacheSizeForOwnerIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Config) CacheSizeForOwnerIDReturns(result1 int) {
	fake.cacheSizeForOwnerIDMutex.Lock()
	defer fake.cacheSizeForOwnerIDMutex.Unlock()
	fake.CacheSizeForOwnerIDStub = nil
	fake.cacheSizeForOwnerIDReturns = struct {
		result1 int
	}{result1}
}

func (fake *Config) CacheSizeForOwnerIDReturnsOnCall(i int, result1 int) {
	fake.cacheSizeForOwnerIDMutex.Lock()
	defer fake.cacheSizeForOwnerIDMutex.Unlock()
	fake.CacheSizeForOwnerIDStub = nil
	if fake.cacheSizeForOwnerIDReturnsOnCall == nil {
		fake.cacheSizeForOwnerIDReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.cacheSizeForOwnerIDReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *Config) TranslatePath(arg1 string) string {
	fake.translatePathMutex.Lock()
	ret, specificReturn := fake.translatePathReturnsOnCall[len(fake.translatePathArgsForCall)]
	fake.translatePathArgsForCall = append(fake.translatePathArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.TranslatePathStub
	fakeReturns := fake.translatePathReturns
	fake.recordInvocation("TranslatePath", []interface{}{arg1})
	fake.translatePathMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Config) TranslatePathCallCount() int {
	fake.translatePathMutex.RLock()
	defer fake.translatePathMutex.RUnlock()
	return len(fake.translatePathArgsForCall)
}

func (fake *Config) TranslatePathCalls(stub func(string) string) {
	fake.translatePathMutex.Lock()
	defer fake.translatePathMutex.Unlock()
	fake.TranslatePathStub = stub
}

func (fake *Config) TranslatePathArgsForCall(i int) string {
	fake.translatePathMutex.RLock()
	defer fake.translatePathMutex.RUnlock()
	argsForCall := fake.translatePathArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Config) TranslatePathReturns(result1 string) {
	fake.translatePathMutex.Lock()
	defer fake.translatePathMutex.Unlock()
	fake.TranslatePathStub = nil
	fake.translatePathReturns = struct {
		result1 string
	}{result1}
}

func (fake *Config) TranslatePathReturnsOnCall(i int, result1 string) {
	fake.translatePathMutex.Lock()
	defer fake.translatePathMutex.Unlock()
	fake.TranslatePathStub = nil
	if fake.translatePathReturnsOnCall == nil {
		fake.translatePathReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.translatePathReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *Config) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Config) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.Config = new(Config)
