// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	drivera "github.com/hyperledger-labs/fabric-token-sdk/token/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/identity/driver"
)

type IdentityStoreService struct {
	AddConfigurationStub        func(context.Context, driver.IdentityConfiguration) error
	addConfigurationMutex       sync.RWMutex
	addConfigurationArgsForCall []struct {
		arg1 context.Context
		arg2 driver.IdentityConfiguration
	}
	addConfigurationReturns struct {
		result1 error
	}
	addConfigurationReturnsOnCall map[int]struct {
		result1 error
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	ConfigurationExistsStub        func(context.Context, string, string, string) (bool, error)
	configurationExistsMutex       sync.RWMutex
	configurationExistsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	configurationExistsReturns struct {
		result1 bool
		result2 error
	}
	configurationExistsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	GetAuditInfoStub        func(context.Context, []byte) ([]byte, error)
	getAuditInfoMutex       sync.RWMutex
	getAuditInfoArgsForCall []struct {
		arg1 context.Context
		arg2 []byte
	}
	getAuditInfoReturns struct {
		result1 []byte
		result2 error
	}
	getAuditInfoReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	GetExistingSignerInfoStub        func(context.Context, ...drivera.Identity) ([]string, error)
	getExistingSignerInfoMutex       sync.RWMutex
	getExistingSignerInfoArgsForCall []struct {
		arg1 context.Context
		arg2 []drivera.Identity
	}
	getExistingSignerInfoReturns struct {
		result1 []string
		result2 error
	}
	getExistingSignerInfoReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	GetSignerInfoStub        func(context.Context, []byte) ([]byte, error)
	getSignerInfoMutex       sync.RWMutex
	getSignerInfoArgsForCall []struct {
		arg1 context.Context
		arg2 []byte
	}
	getSignerInfoReturns struct {
		result1 []byte
		result2 error
	}
	getSignerInfoReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	GetTokenInfoStub        func(context.Context, []byte) ([]byte, []byte, error)
	getTokenInfoMutex       sync.RWMutex
	getTokenInfoArgsForCall []struct {
		arg1 context.Context
		arg2 []byte
	}
	getTokenInfoReturns struct {
		result1 []byte
		result2 []byte
		result3 error
	}
	getTokenInfoReturnsOnCall map[int]struct {
		result1 []byte
		result2 []byte
		result3 error
	}
	IteratorConfigurationsStub        func(context.Context, string) (driver.IdentityConfigurationIterator, error)
	iteratorConfigurationsMutex       sync.RWMutex
	iteratorConfigurationsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	iteratorConfigurationsReturns struct {
		result1 driver.IdentityConfigurationIterator
		result2 error
	}
	iteratorConfigurationsReturnsOnCall map[int]struct {
		result1 driver.IdentityConfigurationIterator
		result2 error
	}
	RegisterIdentityDescriptorStub        func(context.Context, *driver.IdentityDescriptor, drivera.Identity) error
	registerIdentityDescriptorMutex       sync.RWMutex
	registerIdentityDescriptorArgsForCall []struct {
		arg1 context.Context
		arg2 *driver.IdentityDescriptor
		arg3 drivera.Identity
	}
	registerIdentityDescriptorReturns struct {
		result1 error
	}
	registerIdentityDescriptorReturnsOnCall map[int]struct {
		result1 error
	}
	SignerInfoExistsStub        func(context.Context, []byte) (bool, error)
	signerInfoExistsMutex       sync.RWMutex
	signerInfoExistsArgsForCall []struct {
		arg1 context.Context
		arg2 []byte
	}
	signerInfoExistsReturns struct {
		result1 bool
		result2 error
	}
	signerInfoExistsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	StoreIdentityDataStub        func(context.Context, []byte, []byte, []byte, []byte) error
	storeIdentityDataMutex       sync.RWMutex
	storeIdentityDataArgsForCall []struct {
		arg1 context.Context
		arg2 []byte
		arg3 []byte
		arg4 []byte
		arg5 []byte
	}
	storeIdentityDataReturns struct {
		result1 error
	}
	storeIdentityDataReturnsOnCall map[int]struct {
		result1 error
	}
	StoreSignerInfoStub        func(context.Context, drivera.Identity, []byte) error
	storeSignerInfoMutex       sync.RWMutex
	storeSignerInfoArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.Identity
		arg3 []byte
	}
	storeSignerInfoReturns struct {
		result1 error
	}
	storeSignerInfoReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *IdentityStoreService) AddConfiguration(arg1 context.Context, arg2 driver.IdentityConfiguration) error {
	fake.addConfigurationMutex.Lock()
	ret, specificReturn := fake.addConfigurationReturnsOnCall[len(fake.addConfigurationArgsForCall)]
	fake.addConfigurationArgsForCall = append(fake.addConfigurationArgsForCall, struct {
		arg1 context.Context
		arg2 driver.IdentityConfiguration
	}{arg1, arg2})
	stub := fake.AddConfigurationStub
	fakeReturns := fake.addConfigurationReturns
	fake.recordInvocation("AddConfiguration", []interface{}{arg1, arg2})
	fake.addConfigurationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IdentityStoreService) AddConfigurationCallCount() int {
	fake.addConfigurationMutex.RLock()
	defer fake.addConfigurationMutex.RUnlock()
	return len(fake.addConfigurationArgsForCall)
}

func (fake *IdentityStoreService) AddConfigurationCalls(stub func(context.Context, driver.IdentityConfiguration) error) {
	fake.addConfigurationMutex.Lock()
	defer fake.addConfigurationMutex.Unlock()
	fake.AddConfigurationStub = stub
}

func (fake *IdentityStoreService) AddConfigurationArgsForCall(i int) (context.Context, driver.IdentityConfiguration) {
	fake.addConfigurationMutex.RLock()
	defer fake.addConfigurationMutex.RUnlock()
	argsForCall := fake.addConfigurationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IdentityStoreService) AddConfigurationReturns(result1 error) {
	fake.addConfigurationMutex.Lock()
	defer fake.addConfigurationMutex.Unlock()
	fake.AddConfigurationStub = nil
	fake.addConfigurationReturns = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) AddConfigurationReturnsOnCall(i int, result1 error) {
	fake.addConfigurationMutex.Lock()
	defer fake.addConfigurationMutex.Unlock()
	fake.AddConfigurationStub = nil
	if fake.addConfigurationReturnsOnCall == nil {
		fake.addConfigurationReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addConfigurationReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IdentityStoreService) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *IdentityStoreService) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *IdentityStoreService) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) ConfigurationExists(arg1 context.Context, arg2 string, arg3 string, arg4 string) (bool, error) {
	fake.configurationExistsMutex.Lock()
	ret, specificReturn := fake.configurationExistsReturnsOnCall[len(fake.configurationExistsArgsForCall)]
	fake.configurationExistsArgsForCall = append(fake.configurationExistsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.ConfigurationExistsStub
	fakeReturns := fake.configurationExistsReturns
	fake.recordInvocation("ConfigurationExists", []interface{}{arg1, arg2, arg3, arg4})
	fake.configurationExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IdentityStoreService) ConfigurationExistsCallCount() int {
	fake.configurationExistsMutex.RLock()
	defer fake.configurationExistsMutex.RUnlock()
	return len(fake.configurationExistsArgsForCall)
}

func (fake *IdentityStoreService) ConfigurationExistsCalls(stub func(context.Context, string, string, string) (bool, error)) {
	fake.configurationExistsMutex.Lock()
	defer fake.configurationExistsMutex.Unlock()
	fake.ConfigurationExistsStub = stub
}

func (fake *IdentityStoreService) ConfigurationExistsArgsForCall(i int) (context.Context, string, string, string) {
	fake.configurationExistsMutex.RLock()
	defer fake.configurationExistsMutex.RUnlock()
	argsForCall := fake.configurationExistsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *IdentityStoreService) ConfigurationExistsReturns(result1 bool, result2 error) {
	fake.configurationExistsMutex.Lock()
	defer fake.configurationExistsMutex.Unlock()
	fake.ConfigurationExistsStub = nil
	fake.configurationExistsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) ConfigurationExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.configurationExistsMutex.Lock()
	defer fake.configurationExistsMutex.Unlock()
	fake.ConfigurationExistsStub = nil
	if fake.configurationExistsReturnsOnCall == nil {
		fake.configurationExistsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.configurationExistsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) GetAuditInfo(arg1 context.Context, arg2 []byte) ([]byte, error) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.getAuditInfoMutex.Lock()
	ret, specificReturn := fake.getAuditInfoReturnsOnCall[len(fake.getAuditInfoArgsForCall)]
	fake.getAuditInfoArgsForCall = append(fake.getAuditInfoArgsForCall, struct {
		arg1 context.Context
		arg2 []byte
	}{arg1, arg2Copy})
	stub := fake.GetAuditInfoStub
	fakeReturns := fake.getAuditInfoReturns
	fake.recordInvocation("GetAuditInfo", []interface{}{arg1, arg2Copy})
	fake.getAuditInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IdentityStoreService) GetAuditInfoCallCount() int {
	fake.getAuditInfoMutex.RLock()
	defer fake.getAuditInfoMutex.RUnlock()
	return len(fake.getAuditInfoArgsForCall)
}

func (fake *IdentityStoreService) GetAuditInfoCalls(stub func(context.Context, []byte) ([]byte, error)) {
	fake.getAuditInfoMutex.Lock()
	defer fake.getAuditInfoMutex.Unlock()
	fake.GetAuditInfoStub = stub
}

func (fake *IdentityStoreService) GetAuditInfoArgsForCall(i int) (context.Context, []byte) {
	fake.getAuditInfoMutex.RLock()
	defer fake.getAuditInfoMutex.RUnlock()
	argsForCall := fake.getAuditInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IdentityStoreService) GetAuditInfoReturns(result1 []byte, result2 error) {
	fake.getAuditInfoMutex.Lock()
	defer fake.getAuditInfoMutex.Unlock()
	fake.GetAuditInfoStub = nil
	fake.getAuditInfoReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) GetAuditInfoReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.getAuditInfoMutex.Lock()
	defer fake.getAuditInfoMutex.Unlock()
	fake.GetAuditInfoStub = nil
	if fake.getAuditInfoReturnsOnCall == nil {
		fake.getAuditInfoReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.getAuditInfoReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) GetExistingSignerInfo(arg1 context.Context, arg2 ...drivera.Identity) ([]string, error) {
	fake.getExistingSignerInfoMutex.Lock()
	ret, specificReturn := fake.getExistingSignerInfoReturnsOnCall[len(fake.getExistingSignerInfoArgsForCall)]
	fake.getExistingSignerInfoArgsForCall = append(fake.getExistingSignerInfoArgsForCall, struct {
		arg1 context.Context
		arg2 []drivera.Identity
	}{arg1, arg2})
	stub := fake.GetExistingSignerInfoStub
	fakeReturns := fake.getExistingSignerInfoReturns
	fake.recordInvocation("GetExistingSignerInfo", []interface{}{arg1, arg2})
	fake.getExistingSignerInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IdentityStoreService) GetExistingSignerInfoCallCount() int {
	fake.getExistingSignerInfoMutex.RLock()
	defer fake.getExistingSignerInfoMutex.RUnlock()
	return len(fake.getExistingSignerInfoArgsForCall)
}

func (fake *IdentityStoreService) GetExistingSignerInfoCalls(stub func(context.Context, ...drivera.Identity) ([]string, error)) {
	fake.getExistingSignerInfoMutex.Lock()
	defer fake.getExistingSignerInfoMutex.Unlock()
	fake.GetExistingSignerInfoStub = stub
}

func (fake *IdentityStoreService) GetExistingSignerInfoArgsForCall(i int) (context.Context, []drivera.Identity) {
	fake.getExistingSignerInfoMutex.RLock()
	defer fake.getExistingSignerInfoMutex.RUnlock()
	argsForCall := fake.getExistingSignerInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IdentityStoreService) GetExistingSignerInfoReturns(result1 []string, result2 error) {
	fake.getExistingSignerInfoMutex.Lock()
	defer fake.getExistingSignerInfoMutex.Unlock()
	fake.GetExistingSignerInfoStub = nil
	fake.getExistingSignerInfoReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) GetExistingSignerInfoReturnsOnCall(i int, result1 []string, result2 error) {
	fake.getExistingSignerInfoMutex.Lock()
	defer fake.getExistingSignerInfoMutex.Unlock()
	fake.GetExistingSignerInfoStub = nil
	if fake.getExistingSignerInfoReturnsOnCall == nil {
		fake.getExistingSignerInfoReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.getExistingSignerInfoReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) GetSignerInfo(arg1 context.Context, arg2 []byte) ([]byte, error) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.getSignerInfoMutex.Lock()
	ret, specificReturn := fake.getSignerInfoReturnsOnCall[len(fake.getSignerInfoArgsForCall)]
	fake.getSignerInfoArgsForCall = append(fake.getSignerInfoArgsForCall, struct {
		arg1 context.Context
		arg2 []byte
	}{arg1, arg2Copy})
	stub := fake.GetSignerInfoStub
	fakeReturns := fake.getSignerInfoReturns
	fake.recordInvocation("GetSignerInfo", []interface{}{arg1, arg2Copy})
	fake.getSignerInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IdentityStoreService) GetSignerInfoCallCount() int {
	fake.getSignerInfoMutex.RLock()
	defer fake.getSignerInfoMutex.RUnlock()
	return len(fake.getSignerInfoArgsForCall)
}

func (fake *IdentityStoreService) GetSignerInfoCalls(stub func(context.Context, []byte) ([]byte, error)) {
	fake.getSignerInfoMutex.Lock()
	defer fake.getSignerInfoMutex.Unlock()
	fake.GetSignerInfoStub = stub
}

func (fake *IdentityStoreService) GetSignerInfoArgsForCall(i int) (context.Context, []byte) {
	fake.getSignerInfoMutex.RLock()
	defer fake.getSignerInfoMutex.RUnlock()
	argsForCall := fake.getSignerInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IdentityStoreService) GetSignerInfoReturns(result1 []byte, result2 error) {
	fake.getSignerInfoMutex.Lock()
	defer fake.getSignerInfoMutex.Unlock()
	fake.GetSignerInfoStub = nil
	fake.getSignerInfoReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) GetSignerInfoReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.getSignerInfoMutex.Lock()
	defer fake.getSignerInfoMutex.Unlock()
	fake.GetSignerInfoStub = nil
	if fake.getSignerInfoReturnsOnCall == nil {
		fake.getSignerInfoReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.getSignerInfoReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) GetTokenInfo(arg1 context.Context, arg2 []byte) ([]byte, []byte, error) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.getTokenInfoMutex.Lock()
	ret, specificReturn := fake.getTokenInfoReturnsOnCall[len(fake.getTokenInfoArgsForCall)]
	fake.getTokenInfoArgsForCall = append(fake.getTokenInfoArgsForCall, struct {
		arg1 context.Context
		arg2 []byte
	}{arg1, arg2Copy})
	stub := fake.GetTokenInfoStub
	fakeReturns := fake.getTokenInfoReturns
	fake.recordInvocation("GetTokenInfo", []interface{}{arg1, arg2Copy})
	fake.getTokenInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *IdentityStoreService) GetTokenInfoCallCount() int {
	fake.getTokenInfoMutex.RLock()
	defer fake.getTokenInfoMutex.RUnlock()
	return len(fake.getTokenInfoArgsForCall)
}

func (fake *IdentityStoreService) GetTokenInfoCalls(stub func(context.Context, []byte) ([]byte, []byte, error)) {
	fake.getTokenInfoMutex.Lock()
	defer fake.getTokenInfoMutex.Unlock()
	fake.GetTokenInfoStub = stub
}

func (fake *IdentityStoreService) GetTokenInfoArgsForCall(i int) (context.Context, []byte) {
	fake.getTokenInfoMutex.RLock()
	defer fake.getTokenInfoMutex.RUnlock()
	argsForCall := fake.getTokenInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IdentityStoreService) GetTokenInfoReturns(result1 []byte, result2 []byte, result3 error) {
	fake.getTokenInfoMutex.Lock()
	defer fake.getTokenInfoMutex.Unlock()
	fake.GetTokenInfoStub = nil
	fake.getTokenInfoReturns = struct {
		result1 []byte
		result2 []byte
		result3 error
	}{result1, result2, result3}
}

func (fake *IdentityStoreService) GetTokenInfoReturnsOnCall(i int, result1 []byte, result2 []byte, result3 error) {
	fake.getTokenInfoMutex.Lock()
	defer fake.getTokenInfoMutex.Unlock()
	fake.GetTokenInfoStub = nil
	if fake.getTokenInfoReturnsOnCall == nil {
		fake.getTokenInfoReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 []byte
			result3 error
		})
	}
	fake.getTokenInfoReturnsOnCall[i] = struct {
		result1 []byte
		result2 []byte
		result3 error
	}{result1, result2, result3}
}

func (fake *IdentityStoreService) IteratorConfigurations(arg1 context.Context, arg2 string) (driver.IdentityConfigurationIterator, error) {
	fake.iteratorConfigurationsMutex.Lock()
	ret, specificReturn := fake.iteratorConfigurationsReturnsOnCall[len(fake.iteratorConfigurationsArgsForCall)]
	fake.iteratorConfigurationsArgsForCall = append(fake.iteratorConfigurationsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.IteratorConfigurationsStub
	fakeReturns := fake.iteratorConfigurationsReturns
	fake.recordInvocation("IteratorConfigurations", []interface{}{arg1, arg2})
	fake.iteratorConfigurationsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IdentityStoreService) IteratorConfigurationsCallCount() int {
	fake.iteratorConfigurationsMutex.RLock()
	defer fake.iteratorConfigurationsMutex.RUnlock()
	return len(fake.iteratorConfigurationsArgsForCall)
}

func (fake *IdentityStoreService) IteratorConfigurationsCalls(stub func(context.Context, string) (driver.IdentityConfigurationIterator, error)) {
	fake.iteratorConfigurationsMutex.Lock()
	defer fake.iteratorConfigurationsMutex.Unlock()
	fake.IteratorConfigurationsStub = stub
}

func (fake *IdentityStoreService) IteratorConfigurationsArgsForCall(i int) (context.Context, string) {
	fake.iteratorConfigurationsMutex.RLock()
	defer fake.iteratorConfigurationsMutex.RUnlock()
	argsForCall := fake.iteratorConfigurationsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IdentityStoreService) IteratorConfigurationsReturns(result1 driver.IdentityConfigurationIterator, result2 error) {
	fake.iteratorConfigurationsMutex.Lock()
	defer fake.iteratorConfigurationsMutex.Unlock()
	fake.IteratorConfigurationsStub = nil
	fake.iteratorConfigurationsReturns = struct {
		result1 driver.IdentityConfigurationIterator
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) IteratorConfigurationsReturnsOnCall(i int, result1 driver.IdentityConfigurationIterator, result2 error) {
	fake.iteratorConfigurationsMutex.Lock()
	defer fake.iteratorConfigurationsMutex.Unlock()
	fake.IteratorConfigurationsStub = nil
	if fake.iteratorConfigurationsReturnsOnCall == nil {
		fake.iteratorConfigurationsReturnsOnCall = make(map[int]struct {
			result1 driver.IdentityConfigurationIterator
			result2 error
		})
	}
	fake.iteratorConfigurationsReturnsOnCall[i] = struct {
		result1 driver.IdentityConfigurationIterator
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) RegisterIdentityDescriptor(arg1 context.Context, arg2 *driver.IdentityDescriptor, arg3 drivera.Identity) error {
	fake.registerIdentityDescriptorMutex.Lock()
	ret, specificReturn := fake.registerIdentityDescriptorReturnsOnCall[len(fake.registerIdentityDescriptorArgsForCall)]
	fake.registerIdentityDescriptorArgsForCall = append(fake.registerIdentityDescriptorArgsForCall, struct {
		arg1 context.Context
		arg2 *driver.IdentityDescriptor
		arg3 drivera.Identity
	}{arg1, arg2, arg3})
	stub := fake.RegisterIdentityDescriptorStub
	fakeReturns := fake.registerIdentityDescriptorReturns
	fake.recordInvocation("RegisterIdentityDescriptor", []interface{}{arg1, arg2, arg3})
	fake.registerIdentityDescriptorMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IdentityStoreService) RegisterIdentityDescriptorCallCount() int {
	fake.registerIdentityDescriptorMutex.RLock()
	defer fake.registerIdentityDescriptorMutex.RUnlock()
	return len(fake.registerIdentityDescriptorArgsForCall)
}

func (fake *IdentityStoreService) RegisterIdentityDescriptorCalls(stub func(context.Context, *driver.IdentityDescriptor, drivera.Identity) error) {
	fake.registerIdentityDescriptorMutex.Lock()
	defer fake.registerIdentityDescriptorMutex.Unlock()
	fake.RegisterIdentityDescriptorStub = stub
}

func (fake *IdentityStoreService) RegisterIdentityDescriptorArgsForCall(i int) (context.Context, *driver.IdentityDescriptor, drivera.Identity) {
	fake.registerIdentityDescriptorMutex.RLock()
	defer fake.registerIdentityDescriptorMutex.RUnlock()
	argsForCall := fake.registerIdentityDescriptorArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *IdentityStoreService) RegisterIdentityDescriptorReturns(result1 error) {
	fake.registerIdentityDescriptorMutex.Lock()
	defer fake.registerIdentityDescriptorMutex.Unlock()
	fake.RegisterIdentityDescriptorStub = nil
	fake.registerIdentityDescriptorReturns = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) RegisterIdentityDescriptorReturnsOnCall(i int, result1 error) {
	fake.registerIdentityDescriptorMutex.Lock()
	defer fake.registerIdentityDescriptorMutex.Unlock()
	fake.RegisterIdentityDescriptorStub = nil
	if fake.registerIdentityDescriptorReturnsOnCall == nil {
		fake.registerIdentityDescriptorReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.registerIdentityDescriptorReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) SignerInfoExists(arg1 context.Context, arg2 []byte) (bool, error) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.signerInfoExistsMutex.Lock()
	ret, specificReturn := fake.signerInfoExistsReturnsOnCall[len(fake.signerInfoExistsArgsForCall)]
	fake.signerInfoExistsArgsForCall = append(fake.signerInfoExistsArgsForCall, struct {
		arg1 context.Context
		arg2 []byte
	}{arg1, arg2Copy})
	stub := fake.SignerInfoExistsStub
	fakeReturns := fake.signerInfoExistsReturns
	fake.recordInvocation("SignerInfoExists", []interface{}{arg1, arg2Copy})
	fake.signerInfoExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IdentityStoreService) SignerInfoExistsCallCount() int {
	fake.signerInfoExistsMutex.RLock()
	defer fake.signerInfoExistsMutex.RUnlock()
	return len(fake.signerInfoExistsArgsForCall)
}

func (fake *IdentityStoreService) SignerInfoExistsCalls(stub func(context.Context, []byte) (bool, error)) {
	fake.signerInfoExistsMutex.Lock()
	defer fake.signerInfoExistsMutex.Unlock()
	fake.SignerInfoExistsStub = stub
}

func (fake *IdentityStoreService) SignerInfoExistsArgsForCall(i int) (context.Context, []byte) {
	fake.signerInfoExistsMutex.RLock()
	defer fake.signerInfoExistsMutex.RUnlock()
	argsForCall := fake.signerInfoExistsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IdentityStoreService) SignerInfoExistsReturns(result1 bool, result2 error) {
	fake.signerInfoExistsMutex.Lock()
	defer fake.signerInfoExistsMutex.Unlock()
	fake.SignerInfoExistsStub = nil
	fake.signerInfoExistsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) SignerInfoExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.signerInfoExistsMutex.Lock()
	defer fake.signerInfoExistsMutex.Unlock()
	fake.SignerInfoExistsStub = nil
	if fake.signerInfoExistsReturnsOnCall == nil {
		fake.signerInfoExistsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.signerInfoExistsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *IdentityStoreService) StoreIdentityData(arg1 context.Context, arg2 []byte, arg3 []byte, arg4 []byte, arg5 []byte) error {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	var arg4Copy []byte
	if arg4 != nil {
		arg4Copy = make([]byte, len(arg4))
		copy(arg4Copy, arg4)
	}
	var arg5Copy []byte
	if arg5 != nil {
		arg5Copy = make([]byte, len(arg5))
		copy(arg5Copy, arg5)
	}
	fake.storeIdentityDataMutex.Lock()
	ret, specificReturn := fake.storeIdentityDataReturnsOnCall[len(fake.storeIdentityDataArgsForCall)]
	fake.storeIdentityDataArgsForCall = append(fake.storeIdentityDataArgsForCall, struct {
		arg1 context.Context
		arg2 []byte
		arg3 []byte
		arg4 []byte
		arg5 []byte
	}{arg1, arg2Copy, arg3Copy, arg4Copy, arg5Copy})
	stub := fake.StoreIdentityDataStub
	fakeReturns := fake.storeIdentityDataReturns
	fake.recordInvocation("StoreIdentityData", []interface{}{arg1, arg2Copy, arg3Copy, arg4Copy, arg5Copy})
	fake.storeIdentityDataMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IdentityStoreService) StoreIdentityDataCallCount() int {
	fake.storeIdentityDataMutex.RLock()
	defer fake.storeIdentityDataMutex.RUnlock()
	return len(fake.storeIdentityDataArgsForCall)
}

func (fake *IdentityStoreService) StoreIdentityDataCalls(stub func(context.Context, []byte, []byte, []byte, []byte) error) {
	fake.storeIdentityDataMutex.Lock()
	defer fake.storeIdentityDataMutex.Unlock()
	fake.StoreIdentityDataStub = stub
}

func (fake *IdentityStoreService) StoreIdentityDataArgsForCall(i int) (context.Context, []byte, []byte, []byte, []byte) {
	fake.storeIdentityDataMutex.RLock()
	defer fake.storeIdentityDataMutex.RUnlock()
	argsForCall := fake.storeIdentityDataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *IdentityStoreService) StoreIdentityDataReturns(result1 error) {
	fake.storeIdentityDataMutex.Lock()
	defer fake.storeIdentityDataMutex.Unlock()
	fake.StoreIdentityDataStub = nil
	fake.storeIdentityDataReturns = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) StoreIdentityDataReturnsOnCall(i int, result1 error) {
	fake.storeIdentityDataMutex.Lock()
	defer fake.storeIdentityDataMutex.Unlock()
	fake.StoreIdentityDataStub = nil
	if fake.storeIdentityDataReturnsOnCall == nil {
		fake.storeIdentityDataReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.storeIdentityDataReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) StoreSignerInfo(arg1 context.Context, arg2 drivera.Identity, arg3 []byte) error {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.storeSignerInfoMutex.Lock()
	ret, specificReturn := fake.storeSignerInfoReturnsOnCall[len(fake.storeSignerInfoArgsForCall)]
	fake.storeSignerInfoArgsForCall = append(fake.storeSignerInfoArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.Identity
		arg3 []byte
	}{arg1, arg2, arg3Copy})
	stub := fake.StoreSignerInfoStub
	fakeReturns := fake.storeSignerInfoReturns
	fake.recordInvocation("StoreSignerInfo", []interface{}{arg1, arg2, arg3Copy})
	fake.storeSignerInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *IdentityStoreService) StoreSignerInfoCallCount() int {
	fake.storeSignerInfoMutex.RLock()
	defer fake.storeSignerInfoMutex.RUnlock()
	return len(fake.storeSignerInfoArgsForCall)
}

func (fake *IdentityStoreService) StoreSignerInfoCalls(stub func(context.Context, drivera.Identity, []byte) error) {
	fake.storeSignerInfoMutex.Lock()
	defer fake.storeSignerInfoMutex.Unlock()
	fake.StoreSignerInfoStub = stub
}

func (fake *IdentityStoreService) StoreSignerInfoArgsForCall(i int) (context.Context, drivera.Identity, []byte) {
	fake.storeSignerInfoMutex.RLock()
	defer fake.storeSignerInfoMutex.RUnlock()
	argsForCall := fake.storeSignerInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *IdentityStoreService) StoreSignerInfoReturns(result1 error) {
	fake.storeSignerInfoMutex.Lock()
	defer fake.storeSignerInfoMutex.Unlock()
	fake.StoreSignerInfoStub = nil
	fake.storeSignerInfoReturns = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) StoreSignerInfoReturnsOnCall(i int, result1 error) {
	fake.storeSignerInfoMutex.Lock()
	defer fake.storeSignerInfoMutex.Unlock()
	fake.StoreSignerInfoStub = nil
	if fake.storeSignerInfoReturnsOnCall == nil {
		fake.storeSignerInfoReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.storeSignerInfoReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *IdentityStoreService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *IdentityStoreService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.IdentityStoreService = new(IdentityStoreService)
