// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	drivera "github.com/hyperledger-labs/fabric-token-sdk/token/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/identity/driver"
)

type TypedVerifierDeserializer struct {
	DeserializeVerifierStub        func(context.Context, driver.IdentityType, []byte) (drivera.Verifier, error)
	deserializeVerifierMutex       sync.RWMutex
	deserializeVerifierArgsForCall []struct {
		arg1 context.Context
		arg2 driver.IdentityType
		arg3 []byte
	}
	deserializeVerifierReturns struct {
		result1 drivera.Verifier
		result2 error
	}
	deserializeVerifierReturnsOnCall map[int]struct {
		result1 drivera.Verifier
		result2 error
	}
	GetAuditInfoStub        func(context.Context, drivera.Identity, driver.IdentityType, []byte, drivera.AuditInfoProvider) ([]byte, error)
	getAuditInfoMutex       sync.RWMutex
	getAuditInfoArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.Identity
		arg3 driver.IdentityType
		arg4 []byte
		arg5 drivera.AuditInfoProvider
	}
	getAuditInfoReturns struct {
		result1 []byte
		result2 error
	}
	getAuditInfoReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	GetAuditInfoMatcherStub        func(context.Context, drivera.Identity, []byte) (drivera.Matcher, error)
	getAuditInfoMatcherMutex       sync.RWMutex
	getAuditInfoMatcherArgsForCall []struct {
		arg1 context.Context
		arg2 drivera.Identity
		arg3 []byte
	}
	getAuditInfoMatcherReturns struct {
		result1 drivera.Matcher
		result2 error
	}
	getAuditInfoMatcherReturnsOnCall map[int]struct {
		result1 drivera.Matcher
		result2 error
	}
	RecipientsStub        func(drivera.Identity, driver.IdentityType, []byte) ([]drivera.Identity, error)
	recipientsMutex       sync.RWMutex
	recipientsArgsForCall []struct {
		arg1 drivera.Identity
		arg2 driver.IdentityType
		arg3 []byte
	}
	recipientsReturns struct {
		result1 []drivera.Identity
		result2 error
	}
	recipientsReturnsOnCall map[int]struct {
		result1 []drivera.Identity
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TypedVerifierDeserializer) DeserializeVerifier(arg1 context.Context, arg2 driver.IdentityType, arg3 []byte) (drivera.Verifier, error) {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.deserializeVerifierMutex.Lock()
	ret, specificReturn := fake.deserializeVerifierReturnsOnCall[len(fake.deserializeVerifierArgsForCall)]
	fake.deserializeVerifierArgsForCall = append(fake.deserializeVerifierArgsForCall, struct {
		arg1 context.Context
		arg2 driver.IdentityType
		arg3 []byte
	}{arg1, arg2, arg3Copy})
	stub := fake.DeserializeVerifierStub
	fakeReturns := fake.deserializeVerifierReturns
	fake.recordInvocation("DeserializeVerifier", []interface{}{arg1, arg2, arg3Copy})
	fake.deserializeVerifierMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TypedVerifierDeserializer) DeserializeVerifierCallCount() int {
	fake.deserializeVerifierMutex.RLock()
	defer fake.deserializeVerifierMutex.RUnlock()
	return len(fake.deserializeVerifierArgsForCall)
}

func (fake *TypedVerifierDeserializer) DeserializeVerifierCalls(stub func(context.Context, driver.IdentityType, []byte) (drivera.Verifier, error)) {
	fake.deserializeVerifierMutex.Lock()
	defer fake.deserializeVerifierMutex.Unlock()
	fake.DeserializeVerifierStub = stub
}

func (fake *TypedVerifierDeserializer) DeserializeVerifierArgsForCall(i int) (context.Context, driver.IdentityType, []byte) {
	fake.deserializeVerifierMutex.RLock()
	defer fake.deserializeVerifierMutex.RUnlock()
	argsForCall := fake.deserializeVerifierArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *TypedVerifierDeserializer) DeserializeVerifierReturns(result1 drivera.Verifier, result2 error) {
	fake.deserializeVerifierMutex.Lock()
	defer fake.deserializeVerifierMutex.Unlock()
	fake.DeserializeVerifierStub = nil
	fake.deserializeVerifierReturns = struct {
		result1 drivera.Verifier
		result2 error
	}{result1, result2}
}

func (fake *TypedVerifierDeserializer) DeserializeVerifierReturnsOnCall(i int, result1 drivera.Verifier, result2 error) {
	fake.deserializeVerifierMutex.Lock()
	defer fake.deserializeVerifierMutex.Unlock()
	fake.DeserializeVerifierStub = nil
	if fake.deserializeVerifierReturnsOnCall == nil {
		fake.deserializeVerifierReturnsOnCall = make(map[int]struct {
			result1 drivera.Verifier
			result2 error
		})
	}
	fake.deserializeVerifierReturnsOnCall[i] = struct {
		result1 drivera.Verifier
		result2 error
	}{result1, result2}
}

func (fake *TypedVerifierDeserializer) GetAuditInfo(arg1 context.Context, arg2 drivera.Identity, arg3 driver.IdentityType, arg4 []byte, arg5 drivera.AuditInfoProvider) ([]byte, error) {
	var arg4Copy []byte
	if arg4 != nil {
		arg4Copy = make([]byte, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.getAuditInfoMutex.Lock()
	ret, specificReturn := fake.getAuditInfoReturnsOnCall[len(fake.getAuditInfoArgsForCall)]
	fake.getAuditInfoArgsForCall = append(fake.getAuditInfoArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.Identity
		arg3 driver.IdentityType
		arg4 []byte
		arg5 drivera.AuditInfoProvider
	}{arg1, arg2, arg3, arg4Copy, arg5})
	stub := fake.GetAuditInfoStub
	fakeReturns := fake.getAuditInfoReturns
	fake.recordInvocation("GetAuditInfo", []interface{}{arg1, arg2, arg3, arg4Copy, arg5})
	fake.getAuditInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TypedVerifierDeserializer) GetAuditInfoCallCount() int {
	fake.getAuditInfoMutex.RLock()
	defer fake.getAuditInfoMutex.RUnlock()
	return len(fake.getAuditInfoArgsForCall)
}

func (fake *TypedVerifierDeserializer) GetAuditInfoCalls(stub func(context.Context, drivera.Identity, driver.IdentityType, []byte, drivera.AuditInfoProvider) ([]byte, error)) {
	fake.getAuditInfoMutex.Lock()
	defer fake.getAuditInfoMutex.Unlock()
	fake.GetAuditInfoStub = stub
}

func (fake *TypedVerifierDeserializer) GetAuditInfoArgsForCall(i int) (context.Context, drivera.Identity, driver.IdentityType, []byte, drivera.AuditInfoProvider) {
	fake.getAuditInfoMutex.RLock()
	defer fake.getAuditInfoMutex.RUnlock()
	argsForCall := fake.getAuditInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *TypedVerifierDeserializer) GetAuditInfoReturns(result1 []byte, result2 error) {
	fake.getAuditInfoMutex.Lock()
	defer fake.getAuditInfoMutex.Unlock()
	fake.GetAuditInfoStub = nil
	fake.getAuditInfoReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *TypedVerifierDeserializer) GetAuditInfoReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.getAuditInfoMutex.Lock()
	defer fake.getAuditInfoMutex.Unlock()
	fake.GetAuditInfoStub = nil
	if fake.getAuditInfoReturnsOnCall == nil {
		fake.getAuditInfoReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.getAuditInfoReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *TypedVerifierDeserializer) GetAuditInfoMatcher(arg1 context.Context, arg2 drivera.Identity, arg3 []byte) (drivera.Matcher, error) {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.getAuditInfoMatcherMutex.Lock()
	ret, specificReturn := fake.getAuditInfoMatcherReturnsOnCall[len(fake.getAuditInfoMatcherArgsForCall)]
	fake.getAuditInfoMatcherArgsForCall = append(fake.getAuditInfoMatcherArgsForCall, struct {
		arg1 context.Context
		arg2 drivera.Identity
		arg3 []byte
	}{arg1, arg2, arg3Copy})
	stub := fake.GetAuditInfoMatcherStub
	fakeReturns := fake.getAuditInfoMatcherReturns
	fake.recordInvocation("GetAuditInfoMatcher", []interface{}{arg1, arg2, arg3Copy})
	fake.getAuditInfoMatcherMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TypedVerifierDeserializer) GetAuditInfoMatcherCallCount() int {
	fake.getAuditInfoMatcherMutex.RLock()
	defer fake.getAuditInfoMatcherMutex.RUnlock()
	return len(fake.getAuditInfoMatcherArgsForCall)
}

func (fake *TypedVerifierDeserializer) GetAuditInfoMatcherCalls(stub func(context.Context, drivera.Identity, []byte) (drivera.Matcher, error)) {
	fake.getAuditInfoMatcherMutex.Lock()
	defer fake.getAuditInfoMatcherMutex.Unlock()
	fake.GetAuditInfoMatcherStub = stub
}

func (fake *TypedVerifierDeserializer) GetAuditInfoMatcherArgsForCall(i int) (context.Context, drivera.Identity, []byte) {
	fake.getAuditInfoMatcherMutex.RLock()
	defer fake.getAuditInfoMatcherMutex.RUnlock()
	argsForCall := fake.getAuditInfoMatcherArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *TypedVerifierDeserializer) GetAuditInfoMatcherReturns(result1 drivera.Matcher, result2 error) {
	fake.getAuditInfoMatcherMutex.Lock()
	defer fake.getAuditInfoMatcherMutex.Unlock()
	fake.GetAuditInfoMatcherStub = nil
	fake.getAuditInfoMatcherReturns = struct {
		result1 drivera.Matcher
		result2 error
	}{result1, result2}
}

func (fake *TypedVerifierDeserializer) GetAuditInfoMatcherReturnsOnCall(i int, result1 drivera.Matcher, result2 error) {
	fake.getAuditInfoMatcherMutex.Lock()
	defer fake.getAuditInfoMatcherMutex.Unlock()
	fake.GetAuditInfoMatcherStub = nil
	if fake.getAuditInfoMatcherReturnsOnCall == nil {
		fake.getAuditInfoMatcherReturnsOnCall = make(map[int]struct {
			result1 drivera.Matcher
			result2 error
		})
	}
	fake.getAuditInfoMatcherReturnsOnCall[i] = struct {
		result1 drivera.Matcher
		result2 error
	}{result1, result2}
}

func (fake *TypedVerifierDeserializer) Recipients(arg1 drivera.Identity, arg2 driver.IdentityType, arg3 []byte) ([]drivera.Identity, error) {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.recipientsMutex.Lock()
	ret, specificReturn := fake.recipientsReturnsOnCall[len(fake.recipientsArgsForCall)]
	fake.recipientsArgsForCall = append(fake.recipientsArgsForCall, struct {
		arg1 drivera.Identity
		arg2 driver.IdentityType
		arg3 []byte
	}{arg1, arg2, arg3Copy})
	stub := fake.RecipientsStub
	fakeReturns := fake.recipientsReturns
	fake.recordInvocation("Recipients", []interface{}{arg1, arg2, arg3Copy})
	fake.recipientsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TypedVerifierDeserializer) RecipientsCallCount() int {
	fake.recipientsMutex.RLock()
	defer fake.recipientsMutex.RUnlock()
	return len(fake.recipientsArgsForCall)
}

func (fake *TypedVerifierDeserializer) RecipientsCalls(stub func(drivera.Identity, driver.IdentityType, []byte) ([]drivera.Identity, error)) {
	fake.recipientsMutex.Lock()
	defer fake.recipientsMutex.Unlock()
	fake.RecipientsStub = stub
}

func (fake *TypedVerifierDeserializer) RecipientsArgsForCall(i int) (drivera.Identity, driver.IdentityType, []byte) {
	fake.recipientsMutex.RLock()
	defer fake.recipientsMutex.RUnlock()
	argsForCall := fake.recipientsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *TypedVerifierDeserializer) RecipientsReturns(result1 []drivera.Identity, result2 error) {
	fake.recipientsMutex.Lock()
	defer fake.recipientsMutex.Unlock()
	fake.RecipientsStub = nil
	fake.recipientsReturns = struct {
		result1 []drivera.Identity
		result2 error
	}{result1, result2}
}

func (fake *TypedVerifierDeserializer) RecipientsReturnsOnCall(i int, result1 []drivera.Identity, result2 error) {
	fake.recipientsMutex.Lock()
	defer fake.recipientsMutex.Unlock()
	fake.RecipientsStub = nil
	if fake.recipientsReturnsOnCall == nil {
		fake.recipientsReturnsOnCall = make(map[int]struct {
			result1 []drivera.Identity
			result2 error
		})
	}
	fake.recipientsReturnsOnCall[i] = struct {
		result1 []drivera.Identity
		result2 error
	}{result1, result2}
}

func (fake *TypedVerifierDeserializer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TypedVerifierDeserializer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ driver.TypedVerifierDeserializer = new(TypedVerifierDeserializer)
