/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package pp

import (
	"github.com/hyperledger-labs/fabric-smart-client/pkg/utils/errors"
	"github.com/hyperledger-labs/fabric-smart-client/platform/common/driver"
	"github.com/hyperledger-labs/fabric-smart-client/platform/fabricx/core/vault/queryservice"
	"github.com/hyperledger-labs/fabric-token-sdk/token"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/logging"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/network/common/rws/keys"
)

var logger = logging.MustGetLogger()

// PublicParametersService models a service for fetching and loading public parameters.
type PublicParametersService struct {
	tmsProvider *token.ManagementServiceProvider
	qsProvider  queryservice.Provider
	translator  *keys.Translator
}

// NewPublicParametersService returns a new PublicParametersService instance
// for fetching and loading public parameters using a query service provider
// and a TMS provider.
func NewPublicParametersService(tmsProvider *token.ManagementServiceProvider, qsProvider queryservice.Provider) *PublicParametersService {
	return &PublicParametersService{
		tmsProvider: tmsProvider,
		qsProvider:  qsProvider,
		translator:  &keys.Translator{},
	}
}

// LoadPublicParams updates the public parameters for the given TMS ID
// in the token management service provider.
func (f *PublicParametersService) LoadPublicParams(tmsID token.TMSID, ppRaw []byte) error {
	return f.tmsProvider.Update(tmsID, ppRaw)
}

// Fetch retrieves the raw public parameters from the ledger for the specified
// network, channel, and namespace. It uses the setup key generated by
// the translator to query the state.
func (f *PublicParametersService) Fetch(network driver.Network, channel driver.Channel, namespace driver.Namespace) ([]byte, error) {
	qs, err := f.qsProvider.Get(network, channel)
	if err != nil {
		return nil, errors.Wrapf(err, "failed getting query service")
	}
	k, err := f.translator.CreateSetupKey()
	if err != nil {
		return nil, errors.Wrapf(err, "failed creating setup key")
	}
	value, err := qs.GetState(namespace, k)
	if err != nil {
		return nil, errors.Wrapf(err, "failed getting state")
	}
	if value == nil {
		return nil, nil
	}

	return value.Raw, nil
}

// Loader models a loader for public parameters.
type Loader interface {
	// LoadPublicParams loads the public parameters for the given TMS ID.
	LoadPublicParams(TMSID token.TMSID, ppRaw []byte) error
}
