// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-token-sdk/token"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/storage/endorserdb"
)

type EndorserStoreServiceManager struct {
	StoreServiceByTMSIdStub        func(token.TMSID) (*endorserdb.StoreService, error)
	storeServiceByTMSIdMutex       sync.RWMutex
	storeServiceByTMSIdArgsForCall []struct {
		arg1 token.TMSID
	}
	storeServiceByTMSIdReturns struct {
		result1 *endorserdb.StoreService
		result2 error
	}
	storeServiceByTMSIdReturnsOnCall map[int]struct {
		result1 *endorserdb.StoreService
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *EndorserStoreServiceManager) StoreServiceByTMSId(arg1 token.TMSID) (*endorserdb.StoreService, error) {
	fake.storeServiceByTMSIdMutex.Lock()
	ret, specificReturn := fake.storeServiceByTMSIdReturnsOnCall[len(fake.storeServiceByTMSIdArgsForCall)]
	fake.storeServiceByTMSIdArgsForCall = append(fake.storeServiceByTMSIdArgsForCall, struct {
		arg1 token.TMSID
	}{arg1})
	stub := fake.StoreServiceByTMSIdStub
	fakeReturns := fake.storeServiceByTMSIdReturns
	fake.recordInvocation("StoreServiceByTMSId", []interface{}{arg1})
	fake.storeServiceByTMSIdMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EndorserStoreServiceManager) StoreServiceByTMSIdCallCount() int {
	fake.storeServiceByTMSIdMutex.RLock()
	defer fake.storeServiceByTMSIdMutex.RUnlock()
	return len(fake.storeServiceByTMSIdArgsForCall)
}

func (fake *EndorserStoreServiceManager) StoreServiceByTMSIdCalls(stub func(token.TMSID) (*endorserdb.StoreService, error)) {
	fake.storeServiceByTMSIdMutex.Lock()
	defer fake.storeServiceByTMSIdMutex.Unlock()
	fake.StoreServiceByTMSIdStub = stub
}

func (fake *EndorserStoreServiceManager) StoreServiceByTMSIdArgsForCall(i int) token.TMSID {
	fake.storeServiceByTMSIdMutex.RLock()
	defer fake.storeServiceByTMSIdMutex.RUnlock()
	argsForCall := fake.storeServiceByTMSIdArgsForCall[i]
	return argsForCall.arg1
}

func (fake *EndorserStoreServiceManager) StoreServiceByTMSIdReturns(result1 *endorserdb.StoreService, result2 error) {
	fake.storeServiceByTMSIdMutex.Lock()
	defer fake.storeServiceByTMSIdMutex.Unlock()
	fake.StoreServiceByTMSIdStub = nil
	fake.storeServiceByTMSIdReturns = struct {
		result1 *endorserdb.StoreService
		result2 error
	}{result1, result2}
}

func (fake *EndorserStoreServiceManager) StoreServiceByTMSIdReturnsOnCall(i int, result1 *endorserdb.StoreService, result2 error) {
	fake.storeServiceByTMSIdMutex.Lock()
	defer fake.storeServiceByTMSIdMutex.Unlock()
	fake.StoreServiceByTMSIdStub = nil
	if fake.storeServiceByTMSIdReturnsOnCall == nil {
		fake.storeServiceByTMSIdReturnsOnCall = make(map[int]struct {
			result1 *endorserdb.StoreService
			result2 error
		})
	}
	fake.storeServiceByTMSIdReturnsOnCall[i] = struct {
		result1 *endorserdb.StoreService
		result2 error
	}{result1, result2}
}

func (fake *EndorserStoreServiceManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *EndorserStoreServiceManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ endorserdb.StoreServiceManager = new(EndorserStoreServiceManager)
