name: Go test coverage check

runs-on: ubuntu-latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-go@v3

  - name: generate test coverage
    run: make compute-coverage

  - name: check test coverage
    uses: vladopajic/go-test-coverage@v2
    with:
      config: ./.testcoverage.yml