name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GOFLAGS: -mod=mod
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/hyperledger-labs/fabric-token-sdk
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/hyperledger-labs/fabric-token-sdk

    - name: Checkout Fabric Smart Client
      uses: actions/checkout@v2
      with:
        repository: hyperledger-labs/fabric-smart-client
        path: ${{ env.GOPATH }}/src/github.com/hyperledger-labs/fabric-smart-client

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Checks
      run: make checks

    - name: Unit Tests
      run: make unit-tests-race
