name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/hyperledger-labs/fabric-token-sdk
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/hyperledger-labs/fabric-token-sdk

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.6

    - name: Checks
      run: make checks

    - name: Unit Tests
      run: make unit-tests

    - name: Integration Tests
      run: make integration-tests
