// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/common/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/network/fabricx/lookup"
)

type Listener struct {
	OnErrorStub        func(context.Context, driver.PKey, error)
	onErrorMutex       sync.RWMutex
	onErrorArgsForCall []struct {
		arg1 context.Context
		arg2 driver.PKey
		arg3 error
	}
	OnStatusStub        func(context.Context, driver.PKey, []byte)
	onStatusMutex       sync.RWMutex
	onStatusArgsForCall []struct {
		arg1 context.Context
		arg2 driver.PKey
		arg3 []byte
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Listener) OnError(arg1 context.Context, arg2 driver.PKey, arg3 error) {
	fake.onErrorMutex.Lock()
	fake.onErrorArgsForCall = append(fake.onErrorArgsForCall, struct {
		arg1 context.Context
		arg2 driver.PKey
		arg3 error
	}{arg1, arg2, arg3})
	stub := fake.OnErrorStub
	fake.recordInvocation("OnError", []interface{}{arg1, arg2, arg3})
	fake.onErrorMutex.Unlock()
	if stub != nil {
		fake.OnErrorStub(arg1, arg2, arg3)
	}
}

func (fake *Listener) OnErrorCallCount() int {
	fake.onErrorMutex.RLock()
	defer fake.onErrorMutex.RUnlock()
	return len(fake.onErrorArgsForCall)
}

func (fake *Listener) OnErrorCalls(stub func(context.Context, driver.PKey, error)) {
	fake.onErrorMutex.Lock()
	defer fake.onErrorMutex.Unlock()
	fake.OnErrorStub = stub
}

func (fake *Listener) OnErrorArgsForCall(i int) (context.Context, driver.PKey, error) {
	fake.onErrorMutex.RLock()
	defer fake.onErrorMutex.RUnlock()
	argsForCall := fake.onErrorArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Listener) OnStatus(arg1 context.Context, arg2 driver.PKey, arg3 []byte) {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.onStatusMutex.Lock()
	fake.onStatusArgsForCall = append(fake.onStatusArgsForCall, struct {
		arg1 context.Context
		arg2 driver.PKey
		arg3 []byte
	}{arg1, arg2, arg3Copy})
	stub := fake.OnStatusStub
	fake.recordInvocation("OnStatus", []interface{}{arg1, arg2, arg3Copy})
	fake.onStatusMutex.Unlock()
	if stub != nil {
		fake.OnStatusStub(arg1, arg2, arg3)
	}
}

func (fake *Listener) OnStatusCallCount() int {
	fake.onStatusMutex.RLock()
	defer fake.onStatusMutex.RUnlock()
	return len(fake.onStatusArgsForCall)
}

func (fake *Listener) OnStatusCalls(stub func(context.Context, driver.PKey, []byte)) {
	fake.onStatusMutex.Lock()
	defer fake.onStatusMutex.Unlock()
	fake.OnStatusStub = stub
}

func (fake *Listener) OnStatusArgsForCall(i int) (context.Context, driver.PKey, []byte) {
	fake.onStatusMutex.RLock()
	defer fake.onStatusMutex.RUnlock()
	argsForCall := fake.onStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *Listener) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Listener) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ lookup.Listener = new(Listener)
