// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/common/driver"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/network/fabricx/lookup"
)

type QueryService struct {
	GetStateStub        func(driver.Namespace, driver.PKey) (*driver.VaultValue, error)
	getStateMutex       sync.RWMutex
	getStateArgsForCall []struct {
		arg1 driver.Namespace
		arg2 driver.PKey
	}
	getStateReturns struct {
		result1 *driver.VaultValue
		result2 error
	}
	getStateReturnsOnCall map[int]struct {
		result1 *driver.VaultValue
		result2 error
	}
	GetStatesStub        func(map[driver.Namespace][]driver.PKey) (map[driver.Namespace]map[driver.PKey]driver.VaultValue, error)
	getStatesMutex       sync.RWMutex
	getStatesArgsForCall []struct {
		arg1 map[driver.Namespace][]driver.PKey
	}
	getStatesReturns struct {
		result1 map[driver.Namespace]map[driver.PKey]driver.VaultValue
		result2 error
	}
	getStatesReturnsOnCall map[int]struct {
		result1 map[driver.Namespace]map[driver.PKey]driver.VaultValue
		result2 error
	}
	GetTransactionStatusStub        func(string) (int32, error)
	getTransactionStatusMutex       sync.RWMutex
	getTransactionStatusArgsForCall []struct {
		arg1 string
	}
	getTransactionStatusReturns struct {
		result1 int32
		result2 error
	}
	getTransactionStatusReturnsOnCall map[int]struct {
		result1 int32
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *QueryService) GetState(arg1 driver.Namespace, arg2 driver.PKey) (*driver.VaultValue, error) {
	fake.getStateMutex.Lock()
	ret, specificReturn := fake.getStateReturnsOnCall[len(fake.getStateArgsForCall)]
	fake.getStateArgsForCall = append(fake.getStateArgsForCall, struct {
		arg1 driver.Namespace
		arg2 driver.PKey
	}{arg1, arg2})
	stub := fake.GetStateStub
	fakeReturns := fake.getStateReturns
	fake.recordInvocation("GetState", []interface{}{arg1, arg2})
	fake.getStateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *QueryService) GetStateCallCount() int {
	fake.getStateMutex.RLock()
	defer fake.getStateMutex.RUnlock()
	return len(fake.getStateArgsForCall)
}

func (fake *QueryService) GetStateCalls(stub func(driver.Namespace, driver.PKey) (*driver.VaultValue, error)) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = stub
}

func (fake *QueryService) GetStateArgsForCall(i int) (driver.Namespace, driver.PKey) {
	fake.getStateMutex.RLock()
	defer fake.getStateMutex.RUnlock()
	argsForCall := fake.getStateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *QueryService) GetStateReturns(result1 *driver.VaultValue, result2 error) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = nil
	fake.getStateReturns = struct {
		result1 *driver.VaultValue
		result2 error
	}{result1, result2}
}

func (fake *QueryService) GetStateReturnsOnCall(i int, result1 *driver.VaultValue, result2 error) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = nil
	if fake.getStateReturnsOnCall == nil {
		fake.getStateReturnsOnCall = make(map[int]struct {
			result1 *driver.VaultValue
			result2 error
		})
	}
	fake.getStateReturnsOnCall[i] = struct {
		result1 *driver.VaultValue
		result2 error
	}{result1, result2}
}

func (fake *QueryService) GetStates(arg1 map[driver.Namespace][]driver.PKey) (map[driver.Namespace]map[driver.PKey]driver.VaultValue, error) {
	fake.getStatesMutex.Lock()
	ret, specificReturn := fake.getStatesReturnsOnCall[len(fake.getStatesArgsForCall)]
	fake.getStatesArgsForCall = append(fake.getStatesArgsForCall, struct {
		arg1 map[driver.Namespace][]driver.PKey
	}{arg1})
	stub := fake.GetStatesStub
	fakeReturns := fake.getStatesReturns
	fake.recordInvocation("GetStates", []interface{}{arg1})
	fake.getStatesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *QueryService) GetStatesCallCount() int {
	fake.getStatesMutex.RLock()
	defer fake.getStatesMutex.RUnlock()
	return len(fake.getStatesArgsForCall)
}

func (fake *QueryService) GetStatesCalls(stub func(map[driver.Namespace][]driver.PKey) (map[driver.Namespace]map[driver.PKey]driver.VaultValue, error)) {
	fake.getStatesMutex.Lock()
	defer fake.getStatesMutex.Unlock()
	fake.GetStatesStub = stub
}

func (fake *QueryService) GetStatesArgsForCall(i int) map[driver.Namespace][]driver.PKey {
	fake.getStatesMutex.RLock()
	defer fake.getStatesMutex.RUnlock()
	argsForCall := fake.getStatesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *QueryService) GetStatesReturns(result1 map[driver.Namespace]map[driver.PKey]driver.VaultValue, result2 error) {
	fake.getStatesMutex.Lock()
	defer fake.getStatesMutex.Unlock()
	fake.GetStatesStub = nil
	fake.getStatesReturns = struct {
		result1 map[driver.Namespace]map[driver.PKey]driver.VaultValue
		result2 error
	}{result1, result2}
}

func (fake *QueryService) GetStatesReturnsOnCall(i int, result1 map[driver.Namespace]map[driver.PKey]driver.VaultValue, result2 error) {
	fake.getStatesMutex.Lock()
	defer fake.getStatesMutex.Unlock()
	fake.GetStatesStub = nil
	if fake.getStatesReturnsOnCall == nil {
		fake.getStatesReturnsOnCall = make(map[int]struct {
			result1 map[driver.Namespace]map[driver.PKey]driver.VaultValue
			result2 error
		})
	}
	fake.getStatesReturnsOnCall[i] = struct {
		result1 map[driver.Namespace]map[driver.PKey]driver.VaultValue
		result2 error
	}{result1, result2}
}

func (fake *QueryService) GetTransactionStatus(arg1 string) (int32, error) {
	fake.getTransactionStatusMutex.Lock()
	ret, specificReturn := fake.getTransactionStatusReturnsOnCall[len(fake.getTransactionStatusArgsForCall)]
	fake.getTransactionStatusArgsForCall = append(fake.getTransactionStatusArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetTransactionStatusStub
	fakeReturns := fake.getTransactionStatusReturns
	fake.recordInvocation("GetTransactionStatus", []interface{}{arg1})
	fake.getTransactionStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *QueryService) GetTransactionStatusCallCount() int {
	fake.getTransactionStatusMutex.RLock()
	defer fake.getTransactionStatusMutex.RUnlock()
	return len(fake.getTransactionStatusArgsForCall)
}

func (fake *QueryService) GetTransactionStatusCalls(stub func(string) (int32, error)) {
	fake.getTransactionStatusMutex.Lock()
	defer fake.getTransactionStatusMutex.Unlock()
	fake.GetTransactionStatusStub = stub
}

func (fake *QueryService) GetTransactionStatusArgsForCall(i int) string {
	fake.getTransactionStatusMutex.RLock()
	defer fake.getTransactionStatusMutex.RUnlock()
	argsForCall := fake.getTransactionStatusArgsForCall[i]
	return argsForCall.arg1
}

func (fake *QueryService) GetTransactionStatusReturns(result1 int32, result2 error) {
	fake.getTransactionStatusMutex.Lock()
	defer fake.getTransactionStatusMutex.Unlock()
	fake.GetTransactionStatusStub = nil
	fake.getTransactionStatusReturns = struct {
		result1 int32
		result2 error
	}{result1, result2}
}

func (fake *QueryService) GetTransactionStatusReturnsOnCall(i int, result1 int32, result2 error) {
	fake.getTransactionStatusMutex.Lock()
	defer fake.getTransactionStatusMutex.Unlock()
	fake.GetTransactionStatusStub = nil
	if fake.getTransactionStatusReturnsOnCall == nil {
		fake.getTransactionStatusReturnsOnCall = make(map[int]struct {
			result1 int32
			result2 error
		})
	}
	fake.getTransactionStatusReturnsOnCall[i] = struct {
		result1 int32
		result2 error
	}{result1, result2}
}

func (fake *QueryService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *QueryService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ lookup.QueryService = new(QueryService)
